// ==============================================================================
// build.js - Lightweight 0-Dependency Bundler for NFD Cloudflare Worker
// Bundles src/*.js into worker.js for single-file Cloudflare Worker deployment
// ==============================================================================

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DATA_DIR = path.join(__dirname, 'data');
const OUTPUT_FILE = path.join(__dirname, 'worker.js');

const MODULE_ORDER = [
  'config.js',
  'cache.js',
  'telegram.js',
  'moderation.js',
  'pipeline.js',
  'panel.js',
  'admin.js',
  'index.js',
];

function bundle() {
  console.log('Bundling src/*.js into worker.js...');

  const header = [
    '// ==============================================================================',
    '// NFD (No Fraud / Node Forward Bot) - Cloudflare Worker',
    '// NOTE: This file is automatically generated by `node build.js` from `src/`.',
    '// To edit the codebase, modify files in `src/` and run `node build.js`.',
    '// ==============================================================================',
    '',
  ].join('\n');

  // Read data templates if present
  let defaultStartMsg = '';
  let defaultNotifyMsg = '';
  try {
    defaultStartMsg = fs.readFileSync(path.join(DATA_DIR, 'startMessage.md'), 'utf8').trim();
  } catch {}
  try {
    defaultNotifyMsg = fs.readFileSync(path.join(DATA_DIR, 'notification.txt'), 'utf8').trim();
  } catch {}

  const contents = [];

  for (const file of MODULE_ORDER) {
    const filePath = path.join(SRC_DIR, file);
    if (!fs.existsSync(filePath)) {
      console.error(`Missing module file: ${file}`);
      process.exit(1);
    }

    let code = fs.readFileSync(filePath, 'utf8');

    // Replace data imports with inlined strings for config.js
    if (file === 'config.js') {
      code = code.replace(/import\s+defaultStartMessage\s+from\s+['"].*?['"];?/g, `const defaultStartMessage = ${JSON.stringify(defaultStartMsg)};`);
      code = code.replace(/import\s+defaultNotification\s+from\s+['"].*?['"];?/g, `const defaultNotification = ${JSON.stringify(defaultNotifyMsg)};`);
    }

    // Strip ES module imports
    code = code.replace(/^\s*import\s+.*?from\s+['"].*?['"];?\r?\n?/gm, '');
    code = code.replace(/^\s*import\s+['"].*?['"];?\r?\n?/gm, '');

    // Strip "export default { async fetch(...) { ... } };" block completely
    code = code.replace(/export\s+default\s*\{[\s\S]*?\n\};\r?\n?/g, '');

    // Strip ES module named exports: "export const", "export function", "export async function", "export let", "export var"
    code = code.replace(/^\s*export\s+(const|let|var|function|async function|class)\s+/gm, '$1 ');
    code = code.replace(/^\s*export\s*\{[^}]*\};?\r?\n?/gm, '');

    contents.push(`// --- MODULE: ${file} ---\n` + code.trim());
  }

  const bundledCode = header + contents.join('\n\n') + '\n';
  fs.writeFileSync(OUTPUT_FILE, bundledCode, 'utf8');

  console.log(`Successfully generated ${OUTPUT_FILE} (${bundledCode.length} bytes)`);
}

bundle();
