// ==============================================================================
// build.js - Lightweight Bundler with Conditional Tree-Shaking for NFD
// Bundles src/*.js and src/notifiers/*.js into a single worker.js module
//
// 按需打包机制：
// - 外部推送通道登记在 NOTIFIER_MAP：任一环境变量命中即打包对应通道实现
// - 可选功能模块登记在 FEATURE_MODULES，支持两种模式：
//   optIn  —— 配置任一 envs 即打包，未配置注入 stub（适合默认关闭的功能）
//   optOut —— 默认打包，envs 显式设为 false/0/off/no 才裁剪（适合默认开启的功能）
// - 构建期决定裁剪结果：node build.js [--all]
//   --all / BUILD_ALL=true / BUILD_ALL_NOTIFIERS=true / NODE_ENV=test 时全量打包
// ==============================================================================

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DATA_DIR = path.join(__dirname, 'data');
const OUTPUT_FILE = path.join(__dirname, 'worker.js');

// 外部推送子通道：任一环境变量命中即打包对应通道实现
const NOTIFIER_MAP = [
  { key: 'pushdeer', file: 'notifiers/pushdeer.js', env: 'ENV_PUSHDEER_KEY' },
  { key: 'serverchan', file: 'notifiers/serverchan.js', env: 'ENV_SERVERCHAN_KEY' },
];

// 可选功能模块注册表：新增可裁剪功能时在此登记 name / file / mode / envs / stub
const FEATURE_MODULES = [
  {
    name: 'Bot 命令菜单',
    file: 'commands.js',
    mode: 'optIn',
    envs: ['ENV_BOT_COMMANDS'],
    stub: 'export async function registerBotCommands() {}',
  },
  {
    name: '论坛话题自动创建',
    file: 'forum.js',
    mode: 'optIn',
    envs: ['ENV_ENABLE_FORUM_TOPICS'],
    stub: 'export async function resolveForumTopicThreadId() { return null; }',
  },
  {
    name: '远程自定义文案',
    file: 'remote-text.js',
    mode: 'optIn',
    envs: ['ENV_START_MESSAGE_URL', 'ENV_NOTIFICATION_URL'],
    stub: `
export async function fetchStartMessage(fallback) { return fallback; }
export async function fetchNotificationText(fallback) { return fallback; }
`,
  },
  {
    name: '诈骗库检测',
    file: 'fraud.js',
    mode: 'optOut',
    envs: ['ENV_ENABLE_FRAUD_CHECK'],
    stub: 'export async function isFraud() { return false; }',
  },
];

// 与 config.js 的 FEATURE_OFF_VALUES 保持一致
const FEATURE_OFF_VALUES = ['false', '0', 'off', 'no'];

function isEnvConfigured(envs) {
  return envs.some((name) => {
    const val = process.env[name];
    return val && String(val).trim().length > 0;
  });
}

function isFeatureActive(feature, isBuildAll) {
  if (isBuildAll) return true;
  if (feature.mode === 'optOut') {
    const val = String(process.env[feature.envs[0]] || '').trim().toLowerCase();
    return !FEATURE_OFF_VALUES.includes(val);
  }
  return isEnvConfigured(feature.envs);
}

function resolveActiveModules() {
  const isBuildAll = process.argv.includes('--all')
    || process.env.BUILD_ALL === 'true'
    || process.env.BUILD_ALL_NOTIFIERS === 'true'
    || process.env.NODE_ENV === 'test';

  // Find which notifier channels have environment variables configured
  const activeChannels = NOTIFIER_MAP.filter((item) => {
    if (isBuildAll) return true;
    const val = process.env[item.env];
    return val && String(val).trim().length > 0;
  });

  const baseModules = [
    'config.js',
    'cache.js',
    'telegram.js',
  ];

  const notifierModules = [];
  if (activeChannels.length > 0) {
    notifierModules.push('notifiers/base.js');
    for (const ch of activeChannels) {
      notifierModules.push(ch.file);
    }
    notifierModules.push('notifiers/index.js');
    console.log(`  ✔ 外部推送通道: ${activeChannels.map((ch) => ch.key).join(', ')}`);
  } else {
    // Zero external notification channels configured: inject stub dispatcher without bundling any sub-channel files
    notifierModules.push({
      virtualName: 'notifiers/index.js (stub)',
      code: `
// Notification channels disabled / zero-bloat tree-shaken stub
export const notificationProviders = {};
export async function dispatchNotification() {}
`,
    });
    console.log('  ✘ 外部推送通道 -> stub');
  }

  // Optional feature modules: bundle real implementation only when its gate allows
  const featureModules = FEATURE_MODULES.map((feature) => {
    if (isFeatureActive(feature, isBuildAll)) {
      console.log(`  ✔ ${feature.name} (${feature.file})`);
      return feature.file;
    }
    console.log(`  ✘ ${feature.name} (${feature.file}) -> stub`);
    return {
      virtualName: `${feature.file} (stub)`,
      code: `
// Feature disabled: ${feature.envs.join(' / ')} not enabled; tree-shaken stub
${feature.stub}
`,
    };
  });

  const trailingModules = [
    'moderation.js',
    'pipeline.js',
    'panel.js',
    'admin.js',
    'index.js',
  ];

  return [...baseModules, ...notifierModules, ...featureModules, ...trailingModules];
}

function bundle() {
  console.log('Bundling src/*.js into worker.js...');

  const header = [
    '// ==============================================================================',
    '// NFD (No Fraud / Node Forward Bot) - Cloudflare Worker',
    '// NOTE: This file is automatically generated by `node build.js` from `src/`.',
    '// To edit the codebase, modify files in `src/` and run `node build.js`.',
    '// ==============================================================================',
    '',
  ].join('\n');

  let defaultStartMsg = '';
  let defaultNotifyMsg = '';
  try {
    defaultStartMsg = fs.readFileSync(path.join(DATA_DIR, 'startMessage.md'), 'utf8').trim();
  } catch {}
  try {
    defaultNotifyMsg = fs.readFileSync(path.join(DATA_DIR, 'notification.txt'), 'utf8').trim();
  } catch {}

  const contents = [];
  const modules = resolveActiveModules();

  for (const mod of modules) {
    let file = '';
    let code = '';

    if (typeof mod === 'object' && mod.virtualName) {
      file = mod.virtualName;
      code = mod.code;
    } else {
      file = mod;
      const filePath = path.join(SRC_DIR, file);
      if (!fs.existsSync(filePath)) {
        console.error(`Missing module file: ${file}`);
        process.exit(1);
      }
      code = fs.readFileSync(filePath, 'utf8');
    }

    // In config.js, inline the data file contents
    if (file === 'config.js') {
      code = code.replace(/import\s+defaultStartMessage\s+from\s+['"].*?['"];?/g, `const defaultStartMessage = ${JSON.stringify(defaultStartMsg)};`);
      code = code.replace(/import\s+defaultNotification\s+from\s+['"].*?['"];?/g, `const defaultNotification = ${JSON.stringify(defaultNotifyMsg)};`);
    }

    // Strip all ES module imports (both single-line and multi-line)
    code = code.replace(/import\s+[\s\S]*?from\s+['"].*?['"];?\r?\n?/g, '');
    code = code.replace(/import\s+['"].*?['"];?\r?\n?/g, '');

    // Strip named exports: "export const", "export function", "export async function", "export let", "export var"
    code = code.replace(/^\s*export\s+(const|let|var|function|async function|class)\s+/gm, '$1 ');
    code = code.replace(/^\s*export\s*\{[^}]*\};?\r?\n?/gm, '');

    // Keep "export default" only in index.js, remove from any other file if present
    if (file !== 'index.js') {
      code = code.replace(/export\s+default\s*[\s\S]*?;\r?\n?/g, '');
    }

    contents.push(`// --- MODULE: ${file} ---\n` + code.trim());
  }

  const bundledCode = header + contents.join('\n\n') + '\n';
  fs.writeFileSync(OUTPUT_FILE, bundledCode, 'utf8');

  console.log(`Successfully generated ${OUTPUT_FILE} (${bundledCode.length} bytes)`);
}

bundle();
