// ==============================================================================
// NFD (No Fraud / Node Forward Bot) - Cloudflare Worker
// NOTE: This file is automatically generated by `node build.js` from `src/`.
// To edit the codebase, modify files in `src/` and run `node build.js`.
// ==============================================================================
// --- MODULE: config.js ---
// ==============================================================================
// src/config.js - Configuration, Constants & Dynamic Environment Accessors
// ==============================================================================

const defaultStartMessage = "👋🏻 您好 {username}，这里是人偶，需要留言吗！\n\n⬇️ __请在下方输入框发送消息__（或发送媒体），我帮你转达喵";
const defaultNotification = "*人偶小提醒*\n\n1\\. 交易前请确认对方在 NodeSeek 的身份。\n2\\. 付款或交付前，尽量确认商品、账号或服务确实存在。\n3\\. 大额交易建议走论坛中介，人偶会比较安心。\n4\\. 如果感觉不对劲，请及时到论坛或群组反馈喵。";
const WEBHOOK = '/endpoint';
const PARSE_MODE = 'MarkdownV2';
const NOTIFY_INTERVAL = 3600 * 1000;
const FRAUD_CACHE_TTL = 30 * 60 * 1000;
const MESSAGE_MAP_TTL = 30 * 24 * 3600;
function getToken() {
  return getOptionalEnv('ENV_BOT_TOKEN');
}
function getSecret() {
  return getOptionalEnv('ENV_BOT_SECRET');
}
function getAdminUid() {
  return String(getOptionalEnv('ENV_ADMIN_UID', ''));
}
function getForwardChatId() {
  return String(getOptionalEnv('ENV_FORWARD_CHAT_ID', getAdminUid()));
}
function getForwardThreadId() {
  const tid = getOptionalEnv('ENV_FORWARD_THREAD_ID');
  return tid && /^\d+$/.test(tid) ? Number(tid) : null;
}
function getAlertChatId() {
  return String(getOptionalEnv('ENV_ALERT_CHAT_ID', getForwardChatId()));
}
function getAlertThreadId() {
  const tid = getOptionalEnv('ENV_ALERT_THREAD_ID');
  return tid && /^\d+$/.test(tid) ? Number(tid) : null;
}
function getEnableForumTopics() {
  return getOptionalEnv('ENV_ENABLE_FORUM_TOPICS', 'false') === 'true';
}
function getUserAckCooldownMs() {
  return Number(getOptionalEnv('ENV_USER_ACK_COOLDOWN_MS', '30000'));
}
function getCommandWarningCooldownMs() {
  return Number(getOptionalEnv('ENV_COMMAND_WARNING_COOLDOWN_MS', '60000'));
}
function getKeywordViolationTtl() {
  return Number(getOptionalEnv('ENV_KEYWORD_VIOLATION_TTL_SECONDS', String(24 * 3600)));
}
function getFraudDbUrl() {
  return getOptionalEnv('ENV_FRAUD_DB_URL', 'https://raw.githubusercontent.com/ekishion/nfd/main/data/fraud.db');
}
function getKeywordDbUrl() {
  return getOptionalEnv('ENV_KEYWORD_DB_URL', 'https://raw.githubusercontent.com/ekishion/nfd/main/data/keyword.db');
}
function getNotificationUrl() {
  return getOptionalEnv('ENV_NOTIFICATION_URL');
}
function getStartMsgUrl() {
  return getOptionalEnv('ENV_START_MESSAGE_URL');
}
const ADMIN_COMMANDS = new Set([
  '/help',
  '/panel',
  '/config',
  '/stats',
  '/keywords',
  '/addkeyword',
  '/delkeyword',
  '/synckeywords',
  '/block',
  '/unblock',
  '/checkblock',
  '/quick',
  '/q',
  '/quicks',
  '/addquick',
  '/delquick',
  '/away',
  '/back',
  '/user',
  '/tag',
]);
const DEFAULT_START_MESSAGE = typeof defaultStartMessage === 'string' && defaultStartMessage
  ? defaultStartMessage.trim()
  : [
      '👋🏻 您好 {username}，这里是人偶，需要留言吗！',
      '',
      '⬇️ __请在下方输入框发送消息__（或发送媒体），我帮你转达喵',
    ].join('\n');
const DEFAULT_NOTIFICATION = typeof defaultNotification === 'string' && defaultNotification
  ? defaultNotification.trim()
  : [
      '*人偶小提醒*',
      '',
      '1\\. 交易前请确认对方在 NodeSeek 的身份。',
      '2\\. 付款或交付前，尽量确认商品、账号或服务确实存在。',
      '3\\. 大额交易建议走论坛中介，人偶会比较安心。',
      '4\\. 如果感觉不对劲，请及时到论坛或群组反馈喵。',
    ].join('\n');
function getDefaultEnvConfig() {
  return {
    req_username: getOptionalEnv('ENV_REQUIRE_USERNAME', 'false') === 'true',
    req_photo: getOptionalEnv('ENV_REQUIRE_PHOTO', getOptionalEnv('ENV_REQUIRE_AVATAR', 'false')) === 'true',
    auto_block: getOptionalEnv('ENV_AUTO_BLOCK_KEYWORD_VIOLATORS', 'true') !== 'false',
    violation_limit: Number(getOptionalEnv('ENV_KEYWORD_VIOLATION_LIMIT', '3')),
    delay_seconds: Math.max(0, Number(getOptionalEnv('ENV_FORWARD_DELAY_SECONDS', getOptionalEnv('ENV_FORWARD_DELAY', '0')))),
    notice_admin: getOptionalEnv('ENV_KEYWORD_NOTICE_TO_ADMIN', 'true') !== 'false',
    notice_user: getOptionalEnv('ENV_KEYWORD_NOTICE_TO_USER', 'true') !== 'false',
    enable_notify: getOptionalEnv('ENV_ENABLE_NOTIFICATION', 'true') !== 'false',
    flood_protect: getOptionalEnv('ENV_ENABLE_FLOOD_PROTECTION', 'true') !== 'false',
    flood_limit: Number(getOptionalEnv('ENV_FLOOD_LIMIT', '5')),
    flood_window_seconds: Number(getOptionalEnv('ENV_FLOOD_WINDOW_SECONDS', '10')),
    flood_mute_seconds: Number(getOptionalEnv('ENV_FLOOD_MUTE_SECONDS', '60')),
    block_executables: getOptionalEnv('ENV_BLOCK_EXECUTABLES', 'true') !== 'false',
    away_mode: getOptionalEnv('ENV_AWAY_MODE', 'false') === 'true',
    away_message: getOptionalEnv('ENV_AWAY_MESSAGE', '人偶现在外出中，稍后会尽快回复您的留言喵。'),
    forward_chat_id: getForwardChatId(),
    forward_thread_id: getForwardThreadId(),
    alert_chat_id: getAlertChatId(),
    alert_thread_id: getAlertThreadId(),
    enable_forum_topics: getEnableForumTopics(),
  };
}
function getOptionalEnv(name, fallback = '') {
  return Object.prototype.hasOwnProperty.call(globalThis, name) ? String(globalThis[name] ?? '') : fallback;
}
function asArray(value) {
  return Array.isArray(value) ? value : [];
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// --- MODULE: cache.js ---
// ==============================================================================
// src/cache.js - Memory TTL Cache, KV Wrapper & Remote DB Management
// ==============================================================================
const memoryCache = new Map();
const pendingStats = new Map();
const recentUpdates = new Set();

function pruneExpiredMemoryCache() {
  const now = Date.now();
  for (const [key, item] of memoryCache.entries()) {
    if (item.expiresAt <= now) {
      memoryCache.delete(key);
    }
  }
}
function isDuplicateUpdate(updateId) {
  if (!updateId) return false;
  if (recentUpdates.has(updateId)) return true;
  if (recentUpdates.size >= 200) {
    const first = recentUpdates.values().next().value;
    recentUpdates.delete(first);
  }
  recentUpdates.add(updateId);
  return false;
}
function getMemoryCache(key) {
  const item = memoryCache.get(key);
  if (!item) return undefined;
  if (item.expiresAt <= Date.now()) {
    memoryCache.delete(key);
    return undefined;
  }
  return item.value;
}
function setMemoryCache(key, value, ttlMs = 60000) {
  if (memoryCache.size >= 500) {
    pruneExpiredMemoryCache();
  }
  memoryCache.set(key, {
    value,
    expiresAt: Date.now() + ttlMs,
  });
}
function invalidateMemoryCache(key) {
  memoryCache.delete(key);
}
async function kvGetJson(key, fallback = null) {
  const value = await nfd.get(key, { type: 'json' });
  return value === null || value === undefined ? fallback : value;
}
async function kvPutJson(key, value, options = {}) {
  return nfd.put(key, JSON.stringify(value), options);
}
async function cachedKvGetJson(key, ttlMs = 60000, fallback = null) {
  const mem = getMemoryCache(key);
  if (mem !== undefined) return mem;
  const value = await kvGetJson(key, fallback);
  setMemoryCache(key, value, ttlMs);
  return value;
}
async function cachedKvPutJson(key, value, kvOptions = {}, ttlMs = 60000) {
  setMemoryCache(key, value, ttlMs);
  return kvPutJson(key, value, kvOptions);
}

// Runtime Dynamic Settings (KV > Env > Default)
async function getRuntimeConfig() {
  const cached = getMemoryCache('runtime-config');
  if (cached) return cached;

  const kvCfg = await kvGetJson('runtime-settings', {});
  const merged = {
    ...getDefaultEnvConfig(),
    ...(kvCfg && typeof kvCfg === 'object' ? kvCfg : {}),
  };
  setMemoryCache('runtime-config', merged, 60000);
  return merged;
}
async function updateRuntimeConfig(patch) {
  const current = await getRuntimeConfig();
  const next = { ...current, ...patch };
  setMemoryCache('runtime-config', next, 60000);
  await kvPutJson('runtime-settings', next);
  return next;
}
async function incrementStat(name) {
  const count = (pendingStats.get(name) || 0) + 1;
  if (count >= 5) {
    pendingStats.delete(name);
    const key = `stat-${name}`;
    const current = Number((await nfd.get(key)) || 0);
    await nfd.put(key, String(current + count));
  } else {
    pendingStats.set(name, count);
  }
}
async function getStatCount(name) {
  const key = `stat-${name}`;
  const fromKv = Number((await nfd.get(key)) || 0);
  const fromMem = Number(pendingStats.get(name) || 0);
  return fromKv + fromMem;
}
async function checkCooldown(key, cooldownMs) {
  const now = Date.now();
  const mem = getMemoryCache(`cd-${key}`);
  if (mem && now - mem < cooldownMs) return false;

  const lastSentAt = Number((await nfd.get(key)) || 0);
  if (lastSentAt && now - lastSentAt < cooldownMs) {
    setMemoryCache(`cd-${key}`, lastSentAt, cooldownMs);
    return false;
  }

  setMemoryCache(`cd-${key}`, now, cooldownMs);
  await nfd.put(key, String(now));
  return true;
}
async function sendCooldownPlainText(chatId, key, text, cooldownMs) {
  const allowed = await checkCooldown(key, cooldownMs);
  if (!allowed) return null;
  return sendPlainText(chatId, text);
}

// Guest Tagging System
async function getGuestTag(chatId) {
  const key = `guest-tag-${chatId}`;
  return cachedKvGetJson(key, 300000, '');
}
async function setGuestTag(chatId, tag) {
  const key = `guest-tag-${chatId}`;
  if (!tag) {
    invalidateMemoryCache(key);
    await nfd.delete(key);
    return '';
  }
  await cachedKvPutJson(key, tag, {}, 300000);
  return tag;
}

// Forum Topic Mapping System
async function getGuestTopicId(chatId) {
  const key = `guest-topic-${chatId}`;
  return cachedKvGetJson(key, 300000, null);
}
async function setGuestTopicId(chatId, topicId) {
  const key = `guest-topic-${chatId}`;
  const reverseKey = `topic-guest-${topicId}`;
  await Promise.all([
    cachedKvPutJson(key, Number(topicId), {}, 300000),
    cachedKvPutJson(reverseKey, String(chatId), {}, 300000),
  ]);
  return topicId;
}
async function getGuestIdByTopic(topicId) {
  const reverseKey = `topic-guest-${topicId}`;
  return cachedKvGetJson(reverseKey, 300000, null);
}

// Guest Profiling System
async function trackGuestProfile(message) {
  const chatId = String(message.chat.id);
  const key = `profile-${chatId}`;
  const now = Date.now();
  const current = (await kvGetJson(key, null)) || {
    firstSeen: now,
    messageCount: 0,
  };

  const fromUser = message.from || {};
  const nickname = [fromUser.first_name, fromUser.last_name].filter(Boolean).join(' ').trim();

  const updated = {
    chatId,
    userId: String(fromUser.id || message.chat.id),
    firstSeen: current.firstSeen || now,
    lastSeen: now,
    messageCount: Number(current.messageCount || 0) + 1,
    name: nickname || current.name || '',
    username: fromUser.username ? `@${fromUser.username}` : (current.username || ''),
    languageCode: fromUser.language_code || current.languageCode || '',
    chatType: message.chat?.type || current.chatType || '',
    chatTitle: message.chat?.title || current.chatTitle || '',
  };

  setMemoryCache(key, updated, 300000);
  await kvPutJson(key, updated, { expirationTtl: 180 * 24 * 3600 });
  return updated;
}
async function getGuestProfile(chatId) {
  const key = `profile-${chatId}`;
  return cachedKvGetJson(key, 300000, null);
}

// Quick Reply System
async function listQuickReplies() {
  const cacheKey = 'quick-replies-index';
  const cached = getMemoryCache(cacheKey);
  if (cached) return cached;

  const list = asArray(await kvGetJson('quick-replies-list', []));
  setMemoryCache(cacheKey, list, 120000);
  return list;
}
async function getQuickReply(tag) {
  const key = `quick-reply-${tag.toLowerCase()}`;
  return cachedKvGetJson(key, 300000, null);
}
async function setQuickReply(tag, content) {
  const cleanTag = tag.toLowerCase().trim();
  const key = `quick-reply-${cleanTag}`;
  await cachedKvPutJson(key, content, {}, 300000);

  const list = await listQuickReplies();
  if (!list.includes(cleanTag)) {
    const nextList = [...list, cleanTag];
    await cachedKvPutJson('quick-replies-list', nextList, {}, 300000);
    setMemoryCache('quick-replies-index', nextList, 120000);
  }
}
async function deleteQuickReply(tag) {
  const cleanTag = tag.toLowerCase().trim();
  const key = `quick-reply-${cleanTag}`;
  invalidateMemoryCache(key);
  await nfd.delete(key);

  const list = await listQuickReplies();
  const nextList = list.filter((t) => t !== cleanTag);
  await cachedKvPutJson('quick-replies-list', nextList, {}, 300000);
  setMemoryCache('quick-replies-index', nextList, 120000);
}
async function fetchRemoteDb(url, ttl = FRAUD_CACHE_TTL) {
  const cacheKey = `remote-${url}`;
  const cached = getMemoryCache(cacheKey);
  if (cached) return cached;

  const kvBackupKey = `backup-${url}`;
  try {
    const text = await fetch(url).then((r) => r.text());
    const lines = text.split(/\r?\n/).map((v) => v.trim()).filter(Boolean);
    setMemoryCache(cacheKey, lines, ttl);
    // Background backup to KV for offline resilience
    await kvPutJson(kvBackupKey, lines, { expirationTtl: 7 * 24 * 3600 });
    return lines;
  } catch (e) {
    console.log(JSON.stringify({ error: 'fetch-remote-db-failed', url, message: e.message }));
    // Fallback to KV backup if network/remote fails
    const backup = await kvGetJson(kvBackupKey, null);
    if (Array.isArray(backup) && backup.length > 0) {
      setMemoryCache(cacheKey, backup, ttl);
      return backup;
    }
    return [];
  }
}
async function isFraud(id) {
  const lines = await fetchRemoteDb(getFraudDbUrl());
  return lines.includes(String(id));
}
async function fetchKeywordDb() {
  return fetchRemoteDb(getKeywordDbUrl());
}
async function fetchTextOrDefault(url, fallback) {
  if (!url) return fallback;
  const cached = getMemoryCache(`text-${url}`);
  if (cached) return cached;
  try {
    const response = await fetch(url);
    if (response.ok) {
      const text = await response.text();
      setMemoryCache(`text-${url}`, text, 10 * 60 * 1000);
      return text;
    }
    return fallback;
  } catch (error) {
    console.log(JSON.stringify({ error: 'fetch-text-failed', url, message: error.message }));
    return fallback;
  }
}
async function getBotUsername() {
  const cacheKey = 'bot-username';
  const cached = getMemoryCache(cacheKey);
  if (cached) return cached;
  const token = getToken();
  if (!token) return '';
  try {
    const res = await fetch(`https://api.telegram.org/bot${token}/getMe`);
    const data = await res.json();
    if (data.ok && data.result?.username) {
      setMemoryCache(cacheKey, data.result.username, 86400000);
      return data.result.username;
    }
  } catch (err) {
    console.log(JSON.stringify({ error: 'getMe-failed', message: err.message }));
  }
  return '';
}

// --- MODULE: telegram.js ---
// ==============================================================================
// src/telegram.js - Telegram API Client, Message Formatting & Keyboard Builders
// ==============================================================================
function apiUrl(methodName, params = null) {
  const token = getToken();
  const query = params ? `?${new URLSearchParams(params).toString()}` : '';
  return `https://api.telegram.org/bot${token}/${methodName}${query}`;
}
async function requestTelegram(methodName, body = {}) {
  try {
    const response = await fetch(apiUrl(methodName), {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    const data = await response.json();
    if (!data.ok) {
      console.log(JSON.stringify({ methodName, error: data.description, body }));
    }
    return data;
  } catch (error) {
    console.log(JSON.stringify({ methodName, error: error.message, body }));
    return { ok: false, description: error.message };
  }
}
function sendMessage(msg = {}) {
  return requestTelegram('sendMessage', msg);
}
function editMessageText(msg = {}) {
  return requestTelegram('editMessageText', {
    parse_mode: PARSE_MODE,
    link_preview_options: { is_disabled: true },
    ...msg,
  });
}
function copyMessage(msg = {}) {
  return requestTelegram('copyMessage', msg);
}
function forwardMessage(msg = {}) {
  return requestTelegram('forwardMessage', msg);
}
function deleteMessage(msg = {}) {
  return requestTelegram('deleteMessage', msg);
}
function answerCallbackQuery(msg = {}) {
  return requestTelegram('answerCallbackQuery', msg);
}
function createForumTopic(msg = {}) {
  return requestTelegram('createForumTopic', msg);
}
function escapeMarkdown(value = '') {
  return String(value).replace(/[_*[\]()~`>#+\-=|{}.!\\]/g, '\\$&');
}
function sendMarkdown(chatId, text, extra = {}) {
  return sendMessage({
    chat_id: chatId,
    text,
    parse_mode: PARSE_MODE,
    link_preview_options: { is_disabled: true },
    ...extra,
  });
}
function sendPlainText(chatId, text, extra = {}) {
  return sendMessage({
    chat_id: chatId,
    text,
    ...extra,
  });
}
function mdLine(label, value) {
  return `*${escapeMarkdown(label)}:* ${escapeMarkdown(value || '-')}`;
}
function getMessageText(message) {
  return message.text || message.caption || '';
}
function getCommand(message, botUsername = '') {
  const text = (message.text || '').trim();
  if (!text.startsWith('/')) return '';
  const firstToken = text.split(/\s+/)[0];
  const atIndex = firstToken.indexOf('@');
  if (atIndex !== -1) {
    const cmd = firstToken.slice(0, atIndex).toLowerCase();
    const targetBot = firstToken.slice(atIndex + 1).toLowerCase();
    if (botUsername && targetBot !== botUsername.toLowerCase()) {
      return '';
    }
    return cmd;
  }
  return firstToken.toLowerCase();
}
function getCommandArgs(message) {
  const text = (message.text || '').trim();
  const firstSpace = text.search(/\s/);
  return firstSpace === -1 ? '' : text.slice(firstSpace).trim();
}
function buildUserName(user = {}) {
  const nickname = [user.first_name, user.last_name].filter(Boolean).join(' ').trim();
  if (nickname) return nickname;
  if (user.username) return `@${user.username}`;
  return String(user.id || '');
}
function formatStartMessage(template, user) {
  const username = escapeMarkdown(buildUserName(user));
  return template
    .replaceAll('{username}', username)
    .replaceAll('{id}', String(user.id || ''))
    .replaceAll('{name}', username)
    .replaceAll('{用户名}', username);
}
function buildMessageInfo(message, count = 1, tag = '') {
  const user = message.from || {};
  const guestLabel = tag ? `${buildUserName(user)} [${tag}]` : `${buildUserName(user)} (${user.id || message.chat.id})`;
  const lines = [
    '*人偶收到新留言*',
    mdLine('客人', guestLabel),
  ];
  if (user.username) {
    lines.push(mdLine('用户名', `@${user.username}`));
  }
  if (tag) {
    lines.push(mdLine('备注', tag));
  }
  if (message.chat?.type && message.chat.type !== 'private') {
    lines.push(mdLine('来源会话', `${message.chat.title || message.chat.id} / ${message.chat.type}`));
  }
  if (count > 1) {
    lines.push(mdLine('连续留言', `${count} 条`));
  }
  return lines.join('\n');
}
function formatGuestProfile(profile = {}, tag = '', blocked = false, violationCount = 0) {
  const firstSeenStr = profile?.firstSeen ? new Date(profile.firstSeen).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' }) : '-';
  const lastSeenStr = profile?.lastSeen ? new Date(profile.lastSeen).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' }) : '-';

  return [
    '*客人画像档案*',
    mdLine('用户ID', profile?.userId || profile?.chatId || '-'),
    mdLine('备注标签', tag || '无'),
    mdLine('昵称', profile?.name || profile?.firstName || '-'),
    mdLine('用户名', profile?.username ? `@${profile.username.replace(/^@/, '')}` : '-'),
    mdLine('黑名单状态', blocked ? '已静音' : '正常'),
    mdLine('累计留言数', String(profile?.messageCount || 0)),
    mdLine('敏感词违规', String(violationCount || 0)),
    mdLine('首次留言', firstSeenStr),
    mdLine('最后活跃', lastSeenStr),
  ].join('\n');
}
function adminMessageKeyboard() {
  return {
    inline_keyboard: [
      [
        { text: '回复', callback_data: 'reply' },
        { text: '信息', callback_data: 'info' },
        { text: '撤回最近回复', callback_data: 'revoke:last' },
      ],
      [
        { text: '屏蔽', callback_data: 'block' },
        { text: '解除屏蔽', callback_data: 'unblock' },
        { text: '检查', callback_data: 'checkblock' },
      ],
    ],
  };
}
function revokeReplyKeyboard(guestChatId, messageId) {
  return {
    inline_keyboard: [[
      { text: '撤回这条回复', callback_data: `revoke:${guestChatId}:${messageId}` },
    ]],
  };
}

// --- MODULE: moderation.js ---
// ==============================================================================
// src/moderation.js - Moderation Engine (Blacklist, Flood, Dangerous Files, Avatar & Regex Keywords)
// ==============================================================================
import {
  cachedKvGetJson,
  cachedKvPutJson,
  getMemoryCache,
  setMemoryCache,
  kvGetJson,
  kvPutJson,
  incrementStat,
  fetchKeywordDb,
} from './cache.js';
function normalizeMessageText(text = '') {
  if (!text || typeof text !== 'string') return '';
  return text
    // Strip zero-width, invisible & direction marks
    .replace(/[\u200B-\u200F\uFEFF\u2060\u180E\u00AD]/g, '')
    // Convert full-width ASCII to standard half-width
    .replace(/[\uFF01-\uFF5E]/g, (ch) => String.fromCharCode(ch.charCodeAt(0) - 0xfee0))
    // Convert full-width space to standard space
    .replace(/\u3000/g, ' ')
    // Normalize multi-whitespace
    .replace(/\s+/g, ' ')
    .trim();
}
function parseKeywordRule(rawRule) {
  const raw = String(rawRule || '').trim();
  if (!raw) return null;

  const regexMatch = raw.match(/^\/(.+)\/([a-z]*)$/i);
  if (regexMatch) {
    const [, pattern, flags] = regexMatch;
    try {
      const safeFlags = flags.includes('i') ? flags : `${flags}i`;
      const regex = new RegExp(pattern, safeFlags);
      return {
        raw,
        isRegex: true,
        regex,
      };
    } catch (err) {
      console.log(JSON.stringify({ error: 'invalid-regex-rule', raw, message: err.message }));
      return {
        raw,
        isRegex: false,
        text: raw.toLowerCase(),
      };
    }
  }

  return {
    raw,
    isRegex: false,
    text: raw.toLowerCase(),
  };
}
async function isUserBlocked(chatId) {
  return cachedKvGetJson(`isblocked-${chatId}`, 60000, false);
}
async function setUserBlocked(chatId, blocked) {
  return cachedKvPutJson(`isblocked-${chatId}`, blocked, {}, 60000);
}
async function checkFloodLimit(chatId, config) {
  if (!config.flood_protect) return { blocked: false };

  const now = Date.now();
  const muteKey = `flood-mute-${chatId}`;
  const muteUntil = Number(getMemoryCache(muteKey) || (await nfd.get(muteKey)) || 0);
  if (muteUntil > now) {
    return { blocked: true, remainingSeconds: Math.ceil((muteUntil - now) / 1000) };
  }

  const windowMs = (config.flood_window_seconds || 10) * 1000;
  const historyKey = `flood-history-${chatId}`;
  const history = asArray(getMemoryCache(historyKey) || []);
  const validHistory = history.filter((ts) => now - ts < windowMs);
  validHistory.push(now);
  setMemoryCache(historyKey, validHistory, windowMs);

  if (validHistory.length > (config.flood_limit || 5)) {
    const muteSeconds = config.flood_mute_seconds || 60;
    const muteExpires = now + muteSeconds * 1000;
    setMemoryCache(muteKey, muteExpires, muteSeconds * 1000);
    await nfd.put(muteKey, String(muteExpires), { expirationTtl: muteSeconds });
    await incrementStat('flood-blocked');
    return { blocked: true, remainingSeconds: muteSeconds, triggeredNow: true };
  }

  return { blocked: false };
}
function isDangerousDocument(message) {
  const doc = message?.document;
  if (!doc || !doc.file_name) return false;
  const fileName = doc.file_name.toLowerCase();
  const dangerousExts = ['.exe', '.bat', '.apk', '.cmd', '.vbs', '.ps1', '.scr', '.sh', '.jar', '.msi', '.dll', '.pif'];
  return dangerousExts.some((ext) => fileName.endsWith(ext));
}
async function checkUserHasPhoto(userId) {
  const numericId = Number(userId);
  if (!numericId || Number.isNaN(numericId) || numericId <= 0) return true;

  const key = `has-photo-${numericId}`;
  const cached = getMemoryCache(key);
  if (typeof cached === 'boolean') return cached;

  const kvVal = await kvGetJson(key, null);
  if (typeof kvVal === 'boolean') {
    setMemoryCache(key, kvVal, kvVal ? 3600000 : 300000);
    return kvVal;
  }

  try {
    const res = await requestTelegram('getUserProfilePhotos', { user_id: numericId, limit: 1 });
    if (!res.ok) return true; // fail open on error
    const hasPhoto = Boolean(res.result && Number(res.result.total_count) > 0);
    const ttl = hasPhoto ? 3600 : 300;
    setMemoryCache(key, hasPhoto, ttl * 1000);
    await kvPutJson(key, hasPhoto, { expirationTtl: ttl });
    return hasPhoto;
  } catch (e) {
    console.log(JSON.stringify({ error: 'checkUserHasPhoto-failed', userId, message: e.message }));
    return true;
  }
}
async function getKeywordRules() {
  const cacheKey = 'merged-keyword-rules';
  const cached = getMemoryCache(cacheKey);
  if (cached) return cached;

  const fromKv = await cachedKvGetJson('blocked-keywords', 120000, []);
  const fromDb = await fetchKeywordDb();
  const rawList = Array.from(new Set([...fromDb, ...asArray(fromKv)]));

  const parsedRules = rawList.map(parseKeywordRule).filter(Boolean);
  setMemoryCache(cacheKey, parsedRules, 60000);
  return parsedRules;
}
async function findBlockedKeyword(message) {
  const rawContent = getMessageText(message);
  if (!rawContent) return null;

  const normalized = normalizeMessageText(rawContent);
  const lowerNormalized = normalized.toLowerCase();
  const rules = await getKeywordRules();

  for (const rule of rules) {
    if (rule.isRegex && rule.regex) {
      const match = normalized.match(rule.regex);
      if (match) {
        return {
          matched: true,
          rule: rule.raw,
          snippet: match[0],
        };
      }
    } else if (rule.text) {
      if (lowerNormalized.includes(rule.text)) {
        return {
          matched: true,
          rule: rule.raw,
          snippet: rule.raw,
        };
      }
    }
  }

  return null;
}
async function recordKeywordViolation(message, keyword) {
  const chatId = String(message.chat.id);
  const key = `keyword-violation-${chatId}`;
  const current = await kvGetJson(key, { count: 0, expiresAt: 0 });
  const now = Date.now();
  const count = current.expiresAt > now ? Number(current.count || 0) + 1 : 1;
  const ttl = getKeywordViolationTtl();
  const record = {
    count,
    lastKeyword: keyword,
    updatedAt: now,
    expiresAt: now + ttl * 1000,
  };
  await kvPutJson(key, record, { expirationTtl: ttl });
  return record;
}
async function notifyKeywordBlocked(message, matchResult, violation, config) {
  await incrementStat('keyword-blocked');
  if (!config.notice_admin) return null;
  const alertChatId = config.alert_chat_id || getAdminUid();
  if (!alertChatId) return null;

  const ruleName = typeof matchResult === 'string' ? matchResult : matchResult.rule;
  const snippet = typeof matchResult === 'object' && matchResult?.snippet ? matchResult.snippet : '';

  const lines = [
    '*人偶拦下了一条留言*',
    mdLine('触发规则', ruleName),
  ];

  if (snippet && snippet !== ruleName) {
    lines.push(mdLine('命中切片', snippet));
  }

  lines.push(
    mdLine('累计次数', violation.count),
    mdLine('用户ID', message.chat.id),
    mdLine('客人', buildUserName(message.from || {})),
  );

  if (config.auto_block && violation.count >= config.violation_limit) {
    lines.push(mdLine('处理', '已自动拉入黑名单'));
  }
  const extra = config.alert_thread_id ? { message_thread_id: config.alert_thread_id } : {};
  return sendMarkdown(alertChatId, lines.join('\n'), extra);
}

// --- MODULE: pipeline.js ---
// ==============================================================================
// src/pipeline.js - Message Buffering, Delayed Aggregation & Batch Forwarding
// ==============================================================================

import {
  MESSAGE_MAP_TTL,
  NOTIFY_INTERVAL,
  DEFAULT_NOTIFICATION,
  getAdminUid,
  getUserAckCooldownMs,
  getCommandWarningCooldownMs,
  getNotificationUrl,
  asArray,
  sleep,
} from './config.js';
import {
  cachedKvGetJson,
  cachedKvPutJson,
  getMemoryCache,
  setMemoryCache,
  kvGetJson,
  kvPutJson,
  getRuntimeConfig,
  incrementStat,
  sendCooldownPlainText,
  isFraud,
  fetchTextOrDefault,
  getGuestTag,
  trackGuestProfile,
  getGuestTopicId,
  setGuestTopicId,
  getGuestIdByTopic,
} from './cache.js';
import {
  sendMarkdown,
  copyMessage,
  forwardMessage,
  mdLine,
  buildMessageInfo,
  buildUserName,
  adminMessageKeyboard,
  createForumTopic,
} from './telegram.js';
import {
  isUserBlocked,
  setUserBlocked,
  checkUserHasPhoto,
  findBlockedKeyword,
  recordKeywordViolation,
  notifyKeywordBlocked,
  checkFloodLimit,
  isDangerousDocument,
} from './moderation.js';
async function rememberMessageMap(adminMessageId, guestChatId) {
  setMemoryCache(`msg-map-${adminMessageId}`, String(guestChatId), 3600000);
  return kvPutJson(`msg-map-${adminMessageId}`, String(guestChatId), {
    expirationTtl: MESSAGE_MAP_TTL,
  });
}
async function getMappedGuestId(adminMessage) {
  // 1. Check if message is sent inside a Forum Topic
  const threadId = adminMessage?.message_thread_id;
  if (threadId) {
    const topicGuestId = await getGuestIdByTopic(threadId);
    if (topicGuestId) return topicGuestId;
  }

  // 2. Check reply message ID mapping
  const replyMessageId = adminMessage?.reply_to_message?.message_id;
  if (!replyMessageId) return null;
  const cached = getMemoryCache(`msg-map-${replyMessageId}`);
  if (cached) return cached;
  return kvGetJson(`msg-map-${replyMessageId}`, null);
}
async function handleGuestMessage(message) {
  const chatId = String(message.chat.id);
  const config = await getRuntimeConfig();
  const warningCooldown = getCommandWarningCooldownMs();

  // Parallelize analytics, profile update and user check
  const [isBlocked] = await Promise.all([
    isUserBlocked(chatId),
    incrementStat('guest-message'),
    trackGuestProfile(message),
  ]);

  if (isBlocked) {
    await incrementStat('blocked-user-message');
    return sendCooldownPlainText(chatId, `blocked-notice-${chatId}`, '这里暂时不能继续留言了喵。', warningCooldown);
  }

  // Anti-Flood / Rate Limiting
  const floodCheck = await checkFloodLimit(chatId, config);
  if (floodCheck.blocked) {
    return sendCooldownPlainText(
      chatId,
      `flood-notice-${chatId}`,
      `发送消息太频繁啦，请休息 ${floodCheck.remainingSeconds || 60} 秒后再试喵。`,
      warningCooldown,
    );
  }

  // Dangerous document filter
  if (config.block_executables && isDangerousDocument(message)) {
    await incrementStat('executable-blocked');
    return sendCooldownPlainText(
      chatId,
      `exec-block-${chatId}`,
      '抱歉，为了系统安全，不能转达可执行程序或安装包文件喵。',
      warningCooldown,
    );
  }

  if (config.req_username && !message.from?.username) {
    await incrementStat('no-username-blocked');
    return sendCooldownPlainText(
      chatId,
      `no-username-${chatId}`,
      '请先在 Telegram 设置用户名（Username / @xxx）后再留言喵。',
      warningCooldown,
    );
  }

  if (config.req_photo) {
    const userId = message.from?.id || message.chat.id;
    const hasPhoto = await checkUserHasPhoto(userId);
    if (!hasPhoto) {
      await incrementStat('no-photo-blocked');
      return sendCooldownPlainText(
        chatId,
        `no-photo-${chatId}`,
        '请先在 Telegram 设置个人头像后再留言喵。',
        warningCooldown,
      );
    }
  }

  if (config.delay_seconds > 0) {
    return handleDelayedGuestMessage(message, config);
  }

  return processGuestMessageBatch([message], config);
}
async function handleDelayedGuestMessage(message, config) {
  const chatId = String(message.chat.id);
  const batchKey = `pending-msgs-${chatId}`;
  const tokenKey = `pending-token-${chatId}`;

  const current = asArray(await kvGetJson(batchKey, []));
  if (!current.some((m) => m.message_id === message.message_id)) {
    current.push(message);
  }

  const token = `${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  await kvPutJson(batchKey, current, { expirationTtl: 300 });
  await kvPutJson(tokenKey, token, { expirationTtl: 300 });

  if (current.length >= 10) {
    await kvPutJson(batchKey, null, { expirationTtl: 60 });
    await kvPutJson(tokenKey, null, { expirationTtl: 60 });
    return processGuestMessageBatch(current, config);
  }

  await sleep(config.delay_seconds * 1000);

  const activeToken = await kvGetJson(tokenKey, null);
  if (activeToken !== token) {
    return;
  }

  const finalBatch = asArray(await kvGetJson(batchKey, []));
  await kvPutJson(batchKey, null, { expirationTtl: 60 });
  await kvPutJson(tokenKey, null, { expirationTtl: 60 });

  if (!finalBatch.length) return;
  return processGuestMessageBatch(finalBatch, config);
}
async function processGuestMessageBatch(messages, config = null) {
  if (!messages || !messages.length) return;
  if (!config) config = await getRuntimeConfig();

  const firstMessage = messages[0];
  const chatId = String(firstMessage.chat.id);
  const forwardChatId = config.forward_chat_id || getAdminUid();

  const isBlocked = await isUserBlocked(chatId);
  if (isBlocked) {
    await incrementStat('blocked-user-message');
    return;
  }

  let blockedResult = null;
  let violatingMessage = null;
  for (const msg of messages) {
    const match = await findBlockedKeyword(msg);
    if (match && match.matched) {
      blockedResult = match;
      violatingMessage = msg;
      break;
    }
  }

  if (blockedResult) {
    const targetMsg = violatingMessage || firstMessage;
    const violation = await recordKeywordViolation(targetMsg, blockedResult.rule);
    if (config.auto_block && violation.count >= config.violation_limit) {
      await setUserBlocked(chatId, true);
      await incrementStat('keyword-auto-blocked');
    }
    await notifyKeywordBlocked(targetMsg, blockedResult, violation, config);
    if (config.notice_user) {
      const text = violation.count >= config.violation_limit
        ? '多次发送不能转达的内容，这里暂时不能继续留言了喵。'
        : '这条留言含有暂时不能转达的词，人偶先收起来了喵。';
      return sendCooldownPlainText(chatId, `keyword-notice-${chatId}`, text, getCommandWarningCooldownMs());
    }
    return;
  }

  if (!forwardChatId) {
    console.log(JSON.stringify({ error: 'no-forward-chat-id-configured', chatId }));
    return;
  }

  let targetThreadId = config.forward_thread_id || null;

  // Auto-create Forum Topic if enabled for supergroup
  if (config.enable_forum_topics && forwardChatId.startsWith('-')) {
    let topicId = await getGuestTopicId(chatId);
    if (!topicId) {
      const topicName = `${buildUserName(firstMessage.from || {})} (${chatId})`.slice(0, 128);
      const createRes = await createForumTopic({
        chat_id: forwardChatId,
        name: topicName,
      });
      if (createRes.ok && createRes.result?.message_thread_id) {
        topicId = createRes.result.message_thread_id;
        await setGuestTopicId(chatId, topicId);
      }
    }
    if (topicId) {
      targetThreadId = topicId;
    }
  }

  const threadParam = targetThreadId ? { message_thread_id: targetThreadId } : {};
  const guestTag = await getGuestTag(chatId);
  const infoReq = await sendMarkdown(
    forwardChatId,
    buildMessageInfo(firstMessage, messages.length, guestTag),
    threadParam,
  );
  if (infoReq.ok) {
    await rememberMessageMap(infoReq.result.message_id, chatId);
  }

  let deliveredAny = false;
  for (let i = 0; i < messages.length; i++) {
    const msg = messages[i];
    const isLast = i === messages.length - 1;
    const extra = {
      ...threadParam,
      ...(isLast ? { reply_markup: adminMessageKeyboard() } : {}),
    };

    const copyReq = await copyMessage({
      chat_id: forwardChatId,
      from_chat_id: msg.chat.id,
      message_id: msg.message_id,
      ...extra,
    });

    if (copyReq.ok) {
      deliveredAny = true;
      await rememberMessageMap(copyReq.result.message_id, chatId);
      continue;
    }

    const forwardReq = await forwardMessage({
      chat_id: forwardChatId,
      from_chat_id: msg.chat.id,
      message_id: msg.message_id,
      ...threadParam,
    });

    if (forwardReq.ok) {
      deliveredAny = true;
      await rememberMessageMap(forwardReq.result.message_id, chatId);
      continue;
    }

    await sendMarkdown(
      forwardChatId,
      [
        '*人偶转达失败*',
        mdLine('用户ID', chatId),
        mdLine('错误', forwardReq.description || copyReq.description || 'Unknown error'),
      ].join('\n'),
      threadParam,
    );
  }

  if (deliveredAny) {
    await handleGuestDelivered(messages[messages.length - 1], config);
  }
}
async function handleGuestDelivered(message, config = null) {
  if (!config) config = await getRuntimeConfig();
  const chatId = String(message.chat.id);

  if (config.away_mode) {
    const awayMsg = config.away_message || '人偶现在外出中，稍后会尽快回复您的留言喵。';
    await sendCooldownPlainText(chatId, `away-notice-${chatId}`, awayMsg, 1800000); // 30 minutes cooldown
  }

  await sendCooldownPlainText(
    chatId,
    `deliver-ack-${chatId}`,
    '留言已经交给管理人啦，人偶会乖乖等回信喵。',
    getUserAckCooldownMs(),
  );
  await handleNotify(message, config);
}
async function handleNotify(message, config = null) {
  if (!config) config = await getRuntimeConfig();
  const chatId = String(message.chat.id);
  const alertChatId = config.alert_chat_id || getAdminUid();
  if (!alertChatId) return;

  const extra = config.alert_thread_id ? { message_thread_id: config.alert_thread_id } : {};

  if (await isFraud(chatId)) {
    return sendMarkdown(alertChatId, `*诈骗库命中*\n${mdLine('UID', chatId)}`, extra);
  }

  if (!config.enable_notify) return;

  const lastMsgTime = await kvGetJson(`lastmsg-${chatId}`, 0);
  if (!lastMsgTime || Date.now() - Number(lastMsgTime) > NOTIFY_INTERVAL) {
    await nfd.put(`lastmsg-${chatId}`, String(Date.now()));
    const notification = await fetchTextOrDefault(getNotificationUrl(), DEFAULT_NOTIFICATION);
    return sendMarkdown(alertChatId, notification, extra);
  }
}

// --- MODULE: panel.js ---
// ==============================================================================
// src/panel.js - 3-Page Interactive Settings Control Panel
// ==============================================================================

import {
  getRuntimeConfig,
  updateRuntimeConfig,
  invalidateMemoryCache,
} from './cache.js';
import {
  sendMarkdown,
  editMessageText,
  deleteMessage,
  answerCallbackQuery,
} from './telegram.js';
function buildSettingPanel(config, page = 'moderation') {
  const isModeration = page === 'moderation';
  const isForwarding = page === 'forwarding';
  const isDefense = page === 'defense';

  const title = isModeration
    ? '⚙️ *控制面板 \\- 拦截审查设置* (1/3)'
    : isForwarding
      ? '⚙️ *控制面板 \\- 转发与通知设置* (2/3)'
      : '⚙️ *控制面板 \\- 防护与离开设置* (3/3)';

  const lines = [title, ''];

  if (isModeration) {
    lines.push(
      `• *要求设置用户名:* ${config.req_username ? '✅ 已开启' : '❌ 已关闭'}`,
      `• *要求设置个人头像:* ${config.req_photo ? '✅ 已开启' : '❌ 已关闭'}`,
      `• *敏感词多次自动拉黑:* ${config.auto_block ? '✅ 已开启' : '❌ 已关闭'}`,
      `• *敏感词拉黑阈值:* \`${config.violation_limit} 次\``,
      '',
      '_点击下方按钮可直接切换状态或调整阈值：_',
    );
  } else if (isForwarding) {
    const delayText = config.delay_seconds > 0 ? `${config.delay_seconds} 秒` : '关闭 (即时转发)';
    lines.push(
      `• *转发聚合延迟:* \`${delayText}\``,
      `• *敏感词拦截通知管理:* ${config.notice_admin ? '✅ 已开启' : '❌ 已关闭'}`,
      `• *敏感词拦截提示客人:* ${config.notice_user ? '✅ 已开启' : '❌ 已关闭'}`,
      `• *定期交易安全提醒:* ${config.enable_notify ? '✅ 已开启' : '❌ 已关闭'}`,
      '',
      '_点击下方按钮可直接切换状态或调节延迟：_',
    );
  } else {
    lines.push(
      `• *短时防刷屏频控:* ${config.flood_protect ? '✅ 已开启 (10s/5条)' : '❌ 已关闭'}`,
      `• *拦截危险安装包/可执行文件:* ${config.block_executables ? '✅ 已开启' : '❌ 已关闭'}`,
      `• *离开模式 (自动应答):* ${config.away_mode ? '✅ 已开启' : '❌ 已关闭'}`,
      `• *离开提示文案:* \`${(config.away_message || '外出中').slice(0, 30)}\``,
      '',
      '_点击下方按钮可快速切换防护或离开模式：_',
    );
  }

  const text = lines.join('\n');

  const navRow = [
    { text: isModeration ? '🔘 1.拦截审查' : '1.拦截审查', callback_data: 'setting:page:moderation' },
    { text: isForwarding ? '🔘 2.转发通知' : '2.转发通知', callback_data: 'setting:page:forwarding' },
    { text: isDefense ? '🔘 3.防护离开' : '3.防护离开', callback_data: 'setting:page:defense' },
  ];

  let actionRows = [];
  if (isModeration) {
    actionRows = [
      [
        {
          text: `用户名拦截: ${config.req_username ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:req_username',
        },
        {
          text: `头像拦截: ${config.req_photo ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:req_photo',
        },
      ],
      [
        {
          text: `自动拉黑: ${config.auto_block ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:auto_block',
        },
        {
          text: `阈值: ${config.violation_limit}次 🔄`,
          callback_data: 'setting:cycle:violation_limit',
        },
      ],
    ];
  } else if (isForwarding) {
    const delayLabel = config.delay_seconds > 0 ? `${config.delay_seconds}s` : '即时';
    actionRows = [
      [
        {
          text: `转发延迟: ${delayLabel} 🔄`,
          callback_data: 'setting:cycle:delay_seconds',
        },
        {
          text: `通报管理: ${config.notice_admin ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:notice_admin',
        },
      ],
      [
        {
          text: `提示客人: ${config.notice_user ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:notice_user',
        },
        {
          text: `交易提醒: ${config.enable_notify ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:enable_notify',
        },
      ],
    ];
  } else {
    actionRows = [
      [
        {
          text: `防刷频控: ${config.flood_protect ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:flood_protect',
        },
        {
          text: `拦截危险文件: ${config.block_executables ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:block_executables',
        },
      ],
      [
        {
          text: `离开模式: ${config.away_mode ? '✅ 开' : '❌ 关'}`,
          callback_data: 'setting:toggle:away_mode',
        },
      ],
    ];
  }

  const footerRow = [
    { text: '🔄 刷新', callback_data: `setting:refresh:${page}` },
    { text: '❌ 关闭', callback_data: 'setting:close' },
  ];

  const keyboard = {
    inline_keyboard: [navRow, ...actionRows, footerRow],
  };

  return { text, keyboard };
}
async function sendSettingPanel(chatId, page = 'moderation', extra = {}) {
  const config = await getRuntimeConfig();
  const { text, keyboard } = buildSettingPanel(config, page);
  return sendMarkdown(chatId, text, { reply_markup: keyboard, ...extra });
}
async function handleSettingCallback(callbackQuery) {
  const chatId = callbackQuery.message?.chat?.id;
  const data = callbackQuery.data || '';
  const messageId = callbackQuery.message?.message_id;
  const parts = data.split(':');
  const action = parts[1]; // 'page', 'toggle', 'cycle', 'refresh', 'close'
  const key = parts[2];

  if (action === 'close') {
    if (messageId && chatId) {
      await deleteMessage({ chat_id: chatId, message_id: messageId });
    }
    return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '已关闭控制面板' });
  }

  let currentPage = 'moderation';
  let toast = '已更新设置';

  if (action === 'page') {
    currentPage = key || 'moderation';
    toast = `已切换至 ${currentPage === 'forwarding' ? '转发与通知' : currentPage === 'defense' ? '防护与离开' : '拦截审查'}`;
  } else if (action === 'refresh') {
    currentPage = key || 'moderation';
    invalidateMemoryCache('runtime-config');
    toast = '已刷新当前配置';
  } else if (action === 'toggle') {
    const config = await getRuntimeConfig();
    const nextVal = !config[key];
    await updateRuntimeConfig({ [key]: nextVal });
    if (['delay_seconds', 'notice_admin', 'notice_user', 'enable_notify'].includes(key)) {
      currentPage = 'forwarding';
    } else if (['flood_protect', 'block_executables', 'away_mode'].includes(key)) {
      currentPage = 'defense';
    } else {
      currentPage = 'moderation';
    }
    toast = `已${nextVal ? '开启' : '关闭'}`;
  } else if (action === 'cycle') {
    const config = await getRuntimeConfig();
    if (key === 'violation_limit') {
      const limits = [1, 2, 3, 5];
      const nextVal = limits[(limits.indexOf(config.violation_limit) + 1) % limits.length] || 3;
      await updateRuntimeConfig({ violation_limit: nextVal });
      toast = `拉黑阈值调整为: ${nextVal} 次`;
      currentPage = 'moderation';
    } else if (key === 'delay_seconds') {
      const delays = [0, 3, 5, 10, 15];
      const nextVal = delays[(delays.indexOf(config.delay_seconds) + 1) % delays.length] ?? 0;
      await updateRuntimeConfig({ delay_seconds: nextVal });
      toast = nextVal > 0 ? `转发延迟调整为: ${nextVal} 秒` : '转发延迟已关闭 (即时转发)';
      currentPage = 'forwarding';
    }
  }

  const updatedConfig = await getRuntimeConfig();
  const { text, keyboard } = buildSettingPanel(updatedConfig, currentPage);

  if (messageId && chatId) {
    await editMessageText({
      chat_id: chatId,
      message_id: messageId,
      text,
      reply_markup: keyboard,
    });
  }

  return answerCallbackQuery({
    callback_query_id: callbackQuery.id,
    text: toast,
    show_alert: false,
  });
}

// --- MODULE: admin.js ---
// ==============================================================================
// src/admin.js - Admin Commands, Callback Query Router & Guest Management
// ==============================================================================
import {
  kvGetJson,
  kvPutJson,
  cachedKvGetJson,
  cachedKvPutJson,
  invalidateMemoryCache,
  incrementStat,
  getStatCount,
  sendCooldownPlainText,
  fetchKeywordDb,
  getGuestTag,
  setGuestTag,
  getGuestProfile,
  getQuickReply,
  setQuickReply,
  deleteQuickReply,
  listQuickReplies,
  updateRuntimeConfig,
  getRuntimeConfig,
} from './cache.js';
import {
  sendMarkdown,
  sendPlainText,
  copyMessage,
  deleteMessage,
  answerCallbackQuery,
  escapeMarkdown,
  mdLine,
  getCommandArgs,
  buildUserName,
  formatGuestProfile,
  revokeReplyKeyboard,
} from './telegram.js';
async function rememberForceReplyPrompt(promptMessageId, guestChatId) {
  return kvPutJson(`force-reply-${promptMessageId}`, {
    guestChatId: String(guestChatId),
    createdAt: Date.now(),
  }, { expirationTtl: 3600 });
}
async function clearForceReplyPrompt(promptMessageId) {
  return kvPutJson(`force-reply-${promptMessageId}`, null, { expirationTtl: 60 });
}
async function clearRepliedPrompt(message) {
  const promptId = message.reply_to_message?.message_id;
  if (!promptId) return;
  const record = await kvGetJson(`force-reply-${promptId}`, null);
  if (!record) return;
  const chatId = message.chat?.id;
  if (chatId) {
    await deleteMessage({ chat_id: chatId, message_id: promptId });
  }
  await clearForceReplyPrompt(promptId);
}

function getReplyContext(message) {
  const chatId = message?.chat?.id;
  const threadId = message?.message_thread_id;
  const extra = {
    reply_parameters: { message_id: message?.message_id },
    ...(threadId ? { message_thread_id: threadId } : {}),
  };
  return { chatId, threadId, extra };
}
async function handleAdminMessage(message, command) {
  const { chatId, threadId, extra } = getReplyContext(message);
  if (!chatId) return;

  if (command === '/help') return sendAdminHelp(chatId, extra);
  if (command === '/panel' || command === '/config') {
    return sendSettingPanel(chatId, 'moderation', extra);
  }
  if (command === '/stats') return sendStats(chatId, extra);
  if (command === '/keywords') return listKeywords(chatId, extra);
  if (command === '/addkeyword') return addKeyword(message);
  if (command === '/delkeyword') return deleteKeyword(message);
  if (command === '/synckeywords') return syncKeywordDb(chatId, extra);

  if (command === '/block') return handleBlock(message);
  if (command === '/unblock') return handleUnBlock(message);
  if (command === '/checkblock') return checkBlock(message);

  if (command === '/quick' || command === '/q') return handleQuickReply(message);
  if (command === '/quicks') return handleListQuickReplies(chatId, extra);
  if (command === '/addquick') return handleAddQuickReply(message);
  if (command === '/delquick') return handleDeleteQuickReply(message);

  if (command === '/away') return handleAwayMode(message);
  if (command === '/back') return handleBackMode(chatId, extra);
  if (command === '/user') return handleUserProfile(message);
  if (command === '/tag') return handleTagGuest(message);

  const guestChatId = await getMappedGuestId(message);
  if (!guestChatId) {
    return sendAdminHelp(chatId, extra, '请先回复一条人偶转来的留言，或发送管理命令。');
  }

  const copied = await copyMessage({
    chat_id: guestChatId,
    from_chat_id: message.chat.id,
    message_id: message.message_id,
  });

  if (copied.ok) {
    await incrementStat('admin-replied');
    await kvPutJson(`last-reply-${guestChatId}`, {
      chatId: String(guestChatId),
      messageId: copied.result.message_id,
      adminMessageId: message.message_id,
      createdAt: Date.now(),
    });
    await clearRepliedPrompt(message);
    return sendMarkdown(chatId, escapeMarkdown(`人偶已经转达给 UID:${guestChatId} 了喵`), {
      ...extra,
      reply_markup: revokeReplyKeyboard(guestChatId, copied.result.message_id),
    });
  }

  await clearRepliedPrompt(message);
  return sendMarkdown(chatId, escapeMarkdown(`转达失败：${copied.description || 'Unknown error'}`), extra);
}
async function handleGuestAdminCommand(message, command) {
  const chatId = String(message.chat.id);
  const adminUid = getAdminUid();
  await incrementStat('guest-command-warning');
  if (adminUid) {
    await sendMarkdown(
      adminUid,
      [
        '*客人误触管理指令*',
        mdLine('指令', command),
        mdLine('用户ID', chatId),
        mdLine('客人', buildUserName(message.from || {})),
      ].join('\n'),
    );
  }
  return sendCooldownPlainText(
    chatId,
    `warn-admin-cmd-${chatId}`,
    '这个指令是人偶管理人用的喵，请直接发送你想留言的内容即可。',
    getCommandWarningCooldownMs(),
  );
}
async function onCallbackQuery(callbackQuery) {
  const fromId = String(callbackQuery.from?.id || '');
  const adminUid = getAdminUid();
  const chatId = callbackQuery.message?.chat?.id || adminUid;
  const threadId = callbackQuery.message?.message_thread_id;
  const extra = threadId ? { message_thread_id: threadId } : {};

  if (!adminUid || fromId !== adminUid) {
    return answerCallbackQuery({
      callback_query_id: callbackQuery.id,
      text: '这是管理人专用按钮喵。',
      show_alert: false,
    });
  }

  const data = callbackQuery.data || '';
  const adminMessageId = callbackQuery.message?.message_id;

  if (data.startsWith('setting:')) {
    return handleSettingCallback(callbackQuery);
  }

  if (data === 'reply') {
    const guestChatId = await getMappedGuestId(callbackQuery.message);
    if (!guestChatId) {
      return answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: '找不到对应的客人喵，请直接回复原留言。',
        show_alert: true,
      });
    }
    const prompt = await sendMarkdown(
      chatId,
      `请回复这条消息，人偶会转达给 UID:${guestChatId} 喵。`,
      {
        ...extra,
        reply_markup: { force_reply: true, selective: true },
      },
    );
    if (prompt.ok) {
      await rememberForceReplyPrompt(prompt.result.message_id, guestChatId);
    }
    return answerCallbackQuery({
      callback_query_id: callbackQuery.id,
      text: '已生成回复输入框，请回复那条提示消息喵。',
    });
  }

  if (data === 'info') {
    const guestChatId = await getMappedGuestId(callbackQuery.message);
    if (!guestChatId) {
      return answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: '找不到这条留言对应的客人喵。',
        show_alert: true,
      });
    }
    const [profile, tag, blocked, violation] = await Promise.all([
      getGuestProfile(guestChatId),
      getGuestTag(guestChatId),
      isUserBlocked(guestChatId),
      kvGetJson(`keyword-violation-${guestChatId}`, null),
    ]);
    const lines = formatGuestProfile(profile || { userId: guestChatId }, tag, blocked, violation?.count);
    await sendMarkdown(chatId, lines, extra);
    return answerCallbackQuery({ callback_query_id: callbackQuery.id });
  }

  if (data === 'block' || data === 'unblock' || data === 'checkblock') {
    const guestChatId = await getMappedGuestId(callbackQuery.message);
    if (!guestChatId) {
      return answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: '找不到对应的客人喵。',
        show_alert: true,
      });
    }
    if (data === 'block') {
      await setUserBlocked(guestChatId, true);
      await answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: `已将 UID:${guestChatId} 放入静音抽屉。`,
      });
      return sendMarkdown(chatId, escapeMarkdown(`已将 UID:${guestChatId} 放入静音抽屉喵`), extra);
    }
    if (data === 'unblock') {
      await setUserBlocked(guestChatId, false);
      await answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: `已将 UID:${guestChatId} 从静音抽屉取出。`,
      });
      return sendMarkdown(chatId, escapeMarkdown(`已将 UID:${guestChatId} 从静音抽屉取出喵`));
    }
    if (data === 'checkblock') {
      const blocked = await isUserBlocked(guestChatId);
      return answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: `UID:${guestChatId} 当前状态：${blocked ? '已静音' : '正常'}`,
        show_alert: true,
      });
    }
  }

  if (data === 'revoke:last') {
    const guestChatId = await getMappedGuestId(callbackQuery.message);
    if (!guestChatId) {
      return answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: '找不到对应的客人喵。',
        show_alert: true,
      });
    }
    const lastReply = await kvGetJson(`last-reply-${guestChatId}`, null);
    if (!lastReply || !lastReply.messageId) {
      return answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: '没有找到可撤回的回复喵。',
        show_alert: true,
      });
    }
    const result = await deleteMessage({
      chat_id: guestChatId,
      message_id: lastReply.messageId,
    });
    if (result.ok) {
      await kvPutJson(`last-reply-${guestChatId}`, null, { expirationTtl: 60 });
      await answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: '已成功撤回转达的消息。',
      });
      return sendMarkdown(chatId, escapeMarkdown(`已帮管理人撤回发给 UID:${guestChatId} 的上一条消息喵`), extra);
    }
    return answerCallbackQuery({
      callback_query_id: callbackQuery.id,
      text: `撤回失败：${result.description || 'Unknown error'}`,
      show_alert: true,
    });
  }

  if (data.startsWith('revoke:')) {
    const [, targetChatId, targetMsgId] = data.split(':');
    const result = await deleteMessage({
      chat_id: targetChatId,
      message_id: targetMsgId,
    });
    if (result.ok) {
      await deleteMessage({ chat_id: chatId, message_id: adminMessageId });
      return answerCallbackQuery({
        callback_query_id: callbackQuery.id,
        text: '已成功撤回此条消息。',
      });
    }
    return answerCallbackQuery({
      callback_query_id: callbackQuery.id,
      text: `撤回失败：${result.description || 'Unknown error'}`,
      show_alert: true,
    });
  }

  return answerCallbackQuery({ callback_query_id: callbackQuery.id });
}

function resolveTargetGuestId(message, mappedGuestId) {
  const args = getCommandArgs(message);
  if (args && /^\d+$/.test(args)) {
    return args;
  }
  return mappedGuestId;
}
async function handleBlock(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;

  const mappedGuestId = await getMappedGuestId(message);
  const guestChatId = resolveTargetGuestId(message, mappedGuestId);
  if (!guestChatId) return sendAdminHelp(chatId, extra, '用法：回复一条客人的留言发送 /block，或直接发送 `/block 用户ID`。');

  await setUserBlocked(guestChatId, true);
  return sendMarkdown(chatId, escapeMarkdown(`已将 UID:${guestChatId} 放入静音抽屉喵`), extra);
}
async function handleUnBlock(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;

  const mappedGuestId = await getMappedGuestId(message);
  const guestChatId = resolveTargetGuestId(message, mappedGuestId);
  if (!guestChatId) return sendAdminHelp(chatId, extra, '用法：回复一条客人的留言发送 /unblock，或直接发送 `/unblock 用户ID`。');

  await setUserBlocked(guestChatId, false);
  return sendMarkdown(chatId, escapeMarkdown(`已将 UID:${guestChatId} 从静音抽屉取出喵`), extra);
}
async function checkBlock(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;

  const mappedGuestId = await getMappedGuestId(message);
  const guestChatId = resolveTargetGuestId(message, mappedGuestId);
  if (!guestChatId) return sendAdminHelp(chatId, extra, '用法：回复一条客人的留言发送 /checkblock，或直接发送 `/checkblock 用户ID`。');

  const blocked = await isUserBlocked(guestChatId);
  return sendMarkdown(chatId, escapeMarkdown(`UID:${guestChatId} ${blocked ? '正在静音抽屉里' : '可以正常留言'}`), extra);
}
async function handleQuickReply(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;

  const args = getCommandArgs(message).trim();
  if (!args) {
    return sendMarkdown(chatId, '用法：`/quick 标签名`（可简写为 `/q 标签名`）。发送 `/quicks` 可查看已存短语。', extra);
  }

  const mappedGuestId = await getMappedGuestId(message);
  if (!mappedGuestId) {
    return sendMarkdown(chatId, '请先回复客人的留言后再使用快捷短语转达喵。', extra);
  }

  const quickText = await getQuickReply(args);
  if (!quickText) {
    return sendMarkdown(chatId, escapeMarkdown(`未找到标签为「${args}」的快捷短语喵。使用 /addquick ${args} 内容 来添加。`), extra);
  }

  const sent = await sendPlainText(mappedGuestId, quickText);
  if (sent.ok) {
    await incrementStat('admin-replied');
    await kvPutJson(`last-reply-${mappedGuestId}`, {
      chatId: String(mappedGuestId),
      messageId: sent.result.message_id,
      adminMessageId: message.message_id,
      createdAt: Date.now(),
    });
    return sendMarkdown(chatId, escapeMarkdown(`已通过快捷短语「${args}」转达给 UID:${mappedGuestId} 喵`), {
      ...extra,
      reply_markup: revokeReplyKeyboard(mappedGuestId, sent.result.message_id),
    });
  }

  return sendMarkdown(chatId, escapeMarkdown(`快捷回复转达失败：${sent.description || 'Unknown error'}`), extra);
}
async function handleListQuickReplies(chatId, extra = {}) {
  if (!chatId) return;
  const list = await listQuickReplies();
  if (!list.length) {
    return sendMarkdown(chatId, '目前还没有添加快捷短语喵。使用 `/addquick 标签 文本内容` 添加。', extra);
  }
  const lines = list.map((tag) => `\\- \`${escapeMarkdown(tag)}\``);
  return sendMarkdown(chatId, ['*已保存的快捷短语标签*', ...lines, '', '使用 `/quick 标签` 直接回复客人喵。'].join('\n'), extra);
}
async function handleAddQuickReply(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;
  const args = getCommandArgs(message).trim();
  const firstSpace = args.search(/\s/);
  if (firstSpace === -1) {
    return sendMarkdown(chatId, '用法：`/addquick 标签 快捷文本内容`', extra);
  }
  const tag = args.slice(0, firstSpace).trim();
  const content = args.slice(firstSpace).trim();
  if (!tag || !content) {
    return sendMarkdown(chatId, '用法：`/addquick 标签 快捷文本内容`', extra);
  }
  await setQuickReply(tag, content);
  return sendMarkdown(chatId, escapeMarkdown(`已添加快捷短语「${tag}」喵！`), extra);
}
async function handleDeleteQuickReply(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;
  const tag = getCommandArgs(message).trim();
  if (!tag) {
    return sendMarkdown(chatId, '用法：`/delquick 标签`', extra);
  }
  await deleteQuickReply(tag);
  return sendMarkdown(chatId, escapeMarkdown(`已删除快捷短语「${tag}」喵。`), extra);
}
async function handleAwayMode(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;
  const customMsg = getCommandArgs(message).trim();
  const patch = { away_mode: true };
  if (customMsg) {
    patch.away_message = customMsg;
  }
  await updateRuntimeConfig(patch);
  const note = customMsg ? `已设置离开提示文案：\n「${customMsg}」` : '已开启离开自动应答模式。';
  return sendMarkdown(chatId, escapeMarkdown(`${note}\n发送 /back 可恢复在线状态喵。`), extra);
}
async function handleBackMode(chatId, extra = {}) {
  if (!chatId) return;
  await updateRuntimeConfig({ away_mode: false });
  return sendMarkdown(chatId, '已关闭离开模式，恢复正常在线状态喵！', extra);
}
async function handleUserProfile(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;

  const mappedGuestId = await getMappedGuestId(message);
  const targetId = resolveTargetGuestId(message, mappedGuestId);
  if (!targetId) {
    return sendMarkdown(chatId, '用法：回复客人留言发送 `/user`，或直接发送 `/user 用户ID`。', extra);
  }

  const [profile, tag, blocked, violation] = await Promise.all([
    getGuestProfile(targetId),
    getGuestTag(targetId),
    isUserBlocked(targetId),
    kvGetJson(`keyword-violation-${targetId}`, null),
  ]);

  const lines = formatGuestProfile(profile || { userId: targetId }, tag, blocked, violation?.count);
  return sendMarkdown(chatId, lines, extra);
}
async function handleTagGuest(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;

  const args = getCommandArgs(message).trim();
  const mappedGuestId = await getMappedGuestId(message);

  let targetId = mappedGuestId;
  let tagValue = args;

  const match = args.match(/^(\d+)\s+(.+)$/);
  if (match) {
    targetId = match[1];
    tagValue = match[2].trim();
  }

  if (!targetId) {
    return sendMarkdown(chatId, '用法：回复客人留言发送 `/tag 备注名`，或发送 `/tag 用户ID 备注名`。输入 `/tag clear` 可清除备注。', extra);
  }

  if (tagValue.toLowerCase() === 'clear' || tagValue === '清除') {
    await setGuestTag(targetId, '');
    return sendMarkdown(chatId, escapeMarkdown(`已清除 UID:${targetId} 的备注标签喵。`), extra);
  }

  if (!tagValue) {
    const currentTag = await getGuestTag(targetId);
    return sendMarkdown(chatId, escapeMarkdown(`UID:${targetId} 当前备注：${currentTag || '无'}`), extra);
  }

  await setGuestTag(targetId, tagValue);
  return sendMarkdown(chatId, escapeMarkdown(`已为 UID:${targetId} 设置备注标签「${tagValue}」喵！`), extra);
}
async function sendAdminHelp(chatId, extra = {}, prefix = '') {
  const lines = [
    prefix ? `*${escapeMarkdown(prefix)}*\n` : '',
    '*人偶管理手册*',
    '• 直接回复转达的留言即可回信给对应客人',
    '• 发送 `/panel` 或 `/config` 可打开交互式控制面板',
    '• 发送 `/stats` 可查看今日统计与各项拦截指标',
    '• 发送 `/user` 或 `/user UID` 可查看客人画像与违规记录',
    '• 发送 `/tag 备注` 或 `/tag UID 备注` 可为客户设置身份标签',
    '• 发送 `/quick 标签`（或 `/q`）可一键调用快捷短语回复',
    '• 发送 `/quicks` / `/addquick` / `/delquick` 管理快捷短语',
    '• 发送 `/away [离线文案]` / `/back` 管理离开自动应答',
    '• 发送 `/block [UID]` 可将客人加入静音抽屉',
    '• 发送 `/unblock [UID]` 可移出静音抽屉',
    '• 发送 `/checkblock [UID]` 可检查是否在静音抽屉',
    '• 发送 `/keywords` 可查看当前拦截规则与正则表达式',
    '• 发送 `/addkeyword <词或/正则/i>` 可添加屏蔽规则',
    '• 发送 `/delkeyword <规则>` 可删除屏蔽规则',
    '• 发送 `/synckeywords` 可从远程数据库同步规则',
  ].filter(Boolean);

  return sendMarkdown(chatId, lines.join('\n'), extra);
}
async function sendStats(chatId, extra = {}) {
  const now = new Date();
  const dateKey = `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, '0')}-${String(now.getUTCDate()).padStart(2, '0')}`;

  const [
    guestMessages,
    adminReplies,
    blockedUsers,
    keywordBlocked,
    autoBlocked,
    noUsernameBlocked,
    noPhotoBlocked,
    executableBlocked,
    commandWarnings,
  ] = await Promise.all([
    getStatCount('guest-message', dateKey),
    getStatCount('admin-replied', dateKey),
    getStatCount('blocked-user-message', dateKey),
    getStatCount('keyword-blocked', dateKey),
    getStatCount('keyword-auto-blocked', dateKey),
    getStatCount('no-username-blocked', dateKey),
    getStatCount('no-photo-blocked', dateKey),
    getStatCount('executable-blocked', dateKey),
    getStatCount('guest-command-warning', dateKey),
  ]);

  const lines = [
    `*人偶今日运行统计* \\(${escapeMarkdown(dateKey)} UTC\\)`,
    mdLine('收到客人留言', guestMessages),
    mdLine('管理人已回信', adminReplies),
    mdLine('静音名单拦截', blockedUsers),
    mdLine('敏感词规则拦截', keywordBlocked),
    mdLine('敏感词自动拉黑', autoBlocked),
    mdLine('无用户名拦截', noUsernameBlocked),
    mdLine('无头像拦截', noPhotoBlocked),
    mdLine('危险文件拦截', executableBlocked),
    mdLine('误触指令提醒', commandWarnings),
  ];

  return sendMarkdown(chatId, lines.join('\n'), extra);
}
async function listKeywords(chatId, extra = {}) {
  const rules = await getKeywordRules();
  if (!rules.length) {
    return sendMarkdown(chatId, '目前还没有配置敏感词屏蔽规则喵。', extra);
  }
  const lines = rules.map((k) => `\\- \`${escapeMarkdown(k)}\``);
  return sendMarkdown(chatId, ['*当前生效的拦截规则清单*', ...lines].join('\n'), extra);
}
async function addKeyword(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;

  const rawArg = getCommandArgs(message).trim();
  if (!rawArg) {
    return sendMarkdown(chatId, '用法：`/addkeyword 违规词` 或 `/addkeyword /正则/i`', extra);
  }

  if (rawArg.startsWith('/') && rawArg.lastIndexOf('/') > 0) {
    const match = rawArg.match(/^\/(.+)\/([a-z]*)$/i);
    if (match) {
      try {
        new RegExp(match[1], match[2]);
      } catch (err) {
        return sendMarkdown(chatId, escapeMarkdown(`正则表达式语法错误: ${err.message}`), extra);
      }
    }
  }

  const current = await getKeywordRules();
  if (current.includes(rawArg)) {
    return sendMarkdown(chatId, escapeMarkdown(`规则「${rawArg}」已经在清单里了喵`), extra);
  }

  const updated = [...current, rawArg];
  await cachedKvPutJson('keyword-rules', updated, {}, 3600000);
  return sendMarkdown(chatId, escapeMarkdown(`已成功添加拦截规则「${rawArg}」喵！`), extra);
}
async function deleteKeyword(message) {
  const { chatId, extra } = getReplyContext(message);
  if (!chatId) return;

  const rawArg = getCommandArgs(message).trim();
  if (!rawArg) {
    return sendMarkdown(chatId, '用法：`/delkeyword 规则名称`', extra);
  }

  const current = await getKeywordRules();
  const index = current.indexOf(rawArg);
  if (index === -1) {
    return sendMarkdown(chatId, escapeMarkdown(`在清单里没有找到规则「${rawArg}」喵`), extra);
  }

  current.splice(index, 1);
  await cachedKvPutJson('keyword-rules', current, {}, 3600000);
  return sendMarkdown(chatId, escapeMarkdown(`已将规则「${rawArg}」从清单中移除喵`), extra);
}
async function syncKeywordDb(chatId, extra = {}) {
  if (!chatId) return;
  const remote = await fetchKeywordDb();
  if (!remote || !remote.length) {
    return sendMarkdown(chatId, '未能从远程数据库获取到关键词规则喵。', extra);
  }
  const current = await getKeywordRules();
  const merged = Array.from(new Set([...current, ...remote]));
  await cachedKvPutJson('keyword-rules', merged, {}, 3600000);
  return sendMarkdown(chatId, escapeMarkdown(`已完成同步，当前共有 ${merged.length} 条拦截规则生效喵！`), extra);
}

// --- MODULE: index.js ---
// ==============================================================================
// src/index.js - Cloudflare Worker Entry & Webhook Router
// Supports Cloudflare Git Auto-Deploy (Module Worker) & Legacy Service Worker
// ==============================================================================

import {
  WEBHOOK,
  ADMIN_COMMANDS,
  DEFAULT_START_MESSAGE,
  getSecret,
  getAdminUid,
  getForwardChatId,
  getStartMsgUrl,
} from './config.js';
async function handleFetch(request, env = null, ctx = null) {
  if (env) {
    Object.assign(globalThis, env);
  }

  const url = new URL(request.url);
  const secret = getSecret();

  if (url.pathname === WEBHOOK) {
    return handleWebhook(request, ctx);
  } else if (url.pathname === '/registerWebhook') {
    const providedSecret = url.searchParams.get('secret') || request.headers.get('X-Telegram-Bot-Api-Secret-Token') || request.headers.get('x-secret');
    if (secret && providedSecret !== secret) {
      return new Response('Unauthorized: Secret mismatch', { status: 403 });
    }
    return registerWebhook(url);
  } else if (url.pathname === '/unRegisterWebhook') {
    const providedSecret = url.searchParams.get('secret') || request.headers.get('X-Telegram-Bot-Api-Secret-Token') || request.headers.get('x-secret');
    if (secret && providedSecret !== secret) {
      return new Response('Unauthorized: Secret mismatch', { status: 403 });
    }
    return unRegisterWebhook();
  } else {
    return new Response('No handler for this request');
  }
}
async function handleWebhook(request, ctx = null) {
  const secret = getSecret();
  if (secret && request.headers.get('X-Telegram-Bot-Api-Secret-Token') !== secret) {
    return new Response('Unauthorized', { status: 403 });
  }

  const update = await request.json();
  if (ctx && typeof ctx.waitUntil === 'function') {
    ctx.waitUntil(onUpdate(update));
  } else {
    onUpdate(update);
  }
  return new Response('Ok');
}
async function onUpdate(update) {
  try {
    if (update.update_id && isDuplicateUpdate(update.update_id)) {
      return;
    }
    if (update.message) {
      await onMessage(update.message);
    } else if (update.callback_query) {
      await onCallbackQuery(update.callback_query);
    }
  } catch (err) {
    console.log(JSON.stringify({ error: 'onUpdate-failed', message: err.message, stack: err.stack }));
  }
}
async function onMessage(message) {
  if (!message?.chat?.id) return;

  const botUsername = await getBotUsername();
  const command = getCommand(message, botUsername);
  const isGroup = Boolean(message.chat.type && message.chat.type !== 'private');

  const adminUid = getAdminUid();
  const forwardChatId = getForwardChatId();
  const isAdmin = Boolean(
    (adminUid && String(message.chat.id) === adminUid) ||
    (forwardChatId && String(message.chat.id) === forwardChatId) ||
    (adminUid && String(message.from?.id) === adminUid),
  );

  // Group / Supergroup / Channel processing
  if (isGroup) {
    if (!isAdmin) {
      return; // Regular chatter by other group members - ignore
    }
    if (command === '/start') {
      return sendMarkdown(
        message.chat.id,
        '*管理人好喵*，这里是人偶！\n\n发送 `/panel` 可打开交互式控制面板，发送 `/help` 可查看管理手册。',
        message.message_thread_id ? { message_thread_id: message.message_thread_id } : {},
      );
    }
    if (command) {
      return handleAdminMessage(message, command);
    }
    // Check if replying to a guest or typing inside a guest forum topic
    const guestChatId = await getMappedGuestId(message);
    if (guestChatId) {
      return handleAdminMessage(message, '');
    }
    // Regular group chatter, talking to other users, or @ other bots - silently ignore!
    return;
  }

  // Private chat processing
  if (command === '/start') {
    if (isAdmin) {
      return sendMarkdown(
        message.chat.id,
        '*管理人好喵*，这里是人偶！\n\n发送 `/panel` 可打开交互式控制面板，发送 `/help` 可查看管理手册。',
      );
    }
    const startMsg = await fetchTextOrDefault(getStartMsgUrl(), DEFAULT_START_MESSAGE);
    return sendMarkdown(message.chat.id, formatStartMessage(startMsg, message.from || {}));
  }

  if (isAdmin) {
    return handleAdminMessage(message, command);
  }

  if (ADMIN_COMMANDS.has(command)) {
    return handleGuestAdminCommand(message, command);
  }

  return handleGuestMessage(message);
}
async function registerWebhook(requestUrl) {
  const webhookUrl = `${requestUrl.protocol}//${requestUrl.hostname}${WEBHOOK}`;
  const secret = getSecret();
  const r = await fetch(apiUrl('setWebhook'), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      url: webhookUrl,
      secret_token: secret,
      allowed_updates: ['message', 'callback_query'],
      drop_pending_updates: true,
    }),
  }).then((response) => response.json());
  return new Response(r.ok ? 'Ok' : JSON.stringify(r, null, 2));
}
async function unRegisterWebhook() {
  const r = await fetch(apiUrl('setWebhook'), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ url: '' }),
  }).then((response) => response.json());
  return new Response(r.ok ? 'Ok' : JSON.stringify(r, null, 2));
}
