// ==============================================================================
// NFD (No Fraud / Node Forward Bot) - Cloudflare Worker
// NOTE: This file is automatically generated by `node build.js` from `src/`.
// To edit the codebase, modify files in `src/` and run `node build.js`.
// ==============================================================================
// --- MODULE: config.js ---
// ==============================================================================
// src/config.js - Configuration, Constants & Dynamic Environment Accessors
// ==============================================================================

const defaultStartMessage = "👋🏻 您好 {username}，这里是人偶，需要留言吗！\n\n⬇️ __请在下方输入框发送消息__（或发送媒体），我帮你转达喵";
const defaultNotification = "*人偶小提醒*\n\n1\\. 交易前请确认对方在 NodeSeek 的身份。\n2\\. 付款或交付前，尽量确认商品、账号或服务确实存在。\n3\\. 大额交易建议走论坛中介，人偶会比较安心。\n4\\. 如果感觉不对劲，请及时到论坛或群组反馈喵。";
const WEBHOOK = '/endpoint';
const PARSE_MODE = 'MarkdownV2';
const NOTIFY_INTERVAL = 3600 * 1000;
const FRAUD_CACHE_TTL = 30 * 60 * 1000;
const MESSAGE_MAP_TTL = 30 * 24 * 3600;
function getToken() {
  return getOptionalEnv('ENV_BOT_TOKEN');
}
function getSecret() {
  return getOptionalEnv('ENV_BOT_SECRET');
}
function getAdminUid() {
  return String(getOptionalEnv('ENV_ADMIN_UID', ''));
}
function getUserAckCooldownMs() {
  return Number(getOptionalEnv('ENV_USER_ACK_COOLDOWN_MS', '30000'));
}
function getCommandWarningCooldownMs() {
  return Number(getOptionalEnv('ENV_COMMAND_WARNING_COOLDOWN_MS', '60000'));
}
function getKeywordViolationTtl() {
  return Number(getOptionalEnv('ENV_KEYWORD_VIOLATION_TTL_SECONDS', String(24 * 3600)));
}
function getFraudDbUrl() {
  return getOptionalEnv('ENV_FRAUD_DB_URL', 'https://raw.githubusercontent.com/ekishion/nfd/main/data/fraud.db');
}
function getKeywordDbUrl() {
  return getOptionalEnv('ENV_KEYWORD_DB_URL', 'https://raw.githubusercontent.com/ekishion/nfd/main/data/keyword.db');
}
function getNotificationUrl() {
  return getOptionalEnv('ENV_NOTIFICATION_URL');
}
function getStartMsgUrl() {
  return getOptionalEnv('ENV_START_MESSAGE_URL');
}
const ADMIN_COMMANDS = new Set([
  '/help',
  '/panel',
  '/config',
  '/stats',
  '/keywords',
  '/addkeyword',
  '/delkeyword',
  '/synckeywords',
  '/block',
  '/unblock',
  '/checkblock',
]);
const DEFAULT_START_MESSAGE = typeof defaultStartMessage === 'string' && defaultStartMessage
  ? defaultStartMessage.trim()
  : [
      '👋🏻 您好 {username}，这里是人偶，需要留言吗！',
      '',
      '⬇️ __请在下方输入框发送消息__（或发送媒体），我帮你转达喵',
    ].join('\n');
const DEFAULT_NOTIFICATION = typeof defaultNotification === 'string' && defaultNotification
  ? defaultNotification.trim()
  : [
      '*人偶小提醒*',
      '',
      '1\\. 交易前请确认对方在 NodeSeek 的身份。',
      '2\\. 付款或交付前，尽量确认商品、账号或服务确实存在。',
      '3\\. 大额交易建议走论坛中介，人偶会比较安心。',
      '4\\. 如果感觉不对劲，请及时到论坛或群组反馈喵。',
    ].join('\n');
function getDefaultEnvConfig() {
  return {
    req_username: getOptionalEnv('ENV_REQUIRE_USERNAME', 'false') === 'true',
    req_photo: getOptionalEnv('ENV_REQUIRE_PHOTO', getOptionalEnv('ENV_REQUIRE_AVATAR', 'false')) === 'true',
    auto_block: getOptionalEnv('ENV_AUTO_BLOCK_KEYWORD_VIOLATORS', 'true') !== 'false',
    violation_limit: Number(getOptionalEnv('ENV_KEYWORD_VIOLATION_LIMIT', '3')),
    delay_seconds: Math.max(0, Number(getOptionalEnv('ENV_FORWARD_DELAY_SECONDS', getOptionalEnv('ENV_FORWARD_DELAY', '0')))),
    notice_admin: getOptionalEnv('ENV_KEYWORD_NOTICE_TO_ADMIN', 'true') !== 'false',
    notice_user: getOptionalEnv('ENV_KEYWORD_NOTICE_TO_USER', 'true') !== 'false',
    enable_notify: getOptionalEnv('ENV_ENABLE_NOTIFICATION', 'true') !== 'false',
  };
}
function getOptionalEnv(name, fallback = '') {
  return Object.prototype.hasOwnProperty.call(globalThis, name) ? String(globalThis[name] ?? '') : fallback;
}
function asArray(value) {
  return Array.isArray(value) ? value : [];
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// --- MODULE: cache.js ---
// ==============================================================================
// src/cache.js - Memory TTL Cache, KV Wrapper & Remote DB Management
// ==============================================================================
const memoryCache = new Map();
const pendingStats = new Map();

function pruneExpiredMemoryCache() {
  const now = Date.now();
  for (const [key, item] of memoryCache.entries()) {
    if (item.expiresAt <= now) {
      memoryCache.delete(key);
    }
  }
}
function getMemoryCache(key) {
  const item = memoryCache.get(key);
  if (!item) return undefined;
  if (item.expiresAt <= Date.now()) {
    memoryCache.delete(key);
    return undefined;
  }
  return item.value;
}
function setMemoryCache(key, value, ttlMs = 60000) {
  if (memoryCache.size >= 500) {
    pruneExpiredMemoryCache();
  }
  memoryCache.set(key, {
    value,
    expiresAt: Date.now() + ttlMs,
  });
}
function invalidateMemoryCache(key) {
  memoryCache.delete(key);
}
async function kvGetJson(key, fallback = null) {
  const value = await nfd.get(key, { type: 'json' });
  return value === null || value === undefined ? fallback : value;
}
async function kvPutJson(key, value, options = {}) {
  return nfd.put(key, JSON.stringify(value), options);
}
async function cachedKvGetJson(key, ttlMs = 60000, fallback = null) {
  const mem = getMemoryCache(key);
  if (mem !== undefined) return mem;
  const value = await kvGetJson(key, fallback);
  setMemoryCache(key, value, ttlMs);
  return value;
}
async function cachedKvPutJson(key, value, kvOptions = {}, ttlMs = 60000) {
  setMemoryCache(key, value, ttlMs);
  return kvPutJson(key, value, kvOptions);
}

// Runtime Dynamic Settings (KV > Env > Default)
async function getRuntimeConfig() {
  const cached = getMemoryCache('runtime-config');
  if (cached) return cached;

  const kvCfg = await kvGetJson('runtime-settings', {});
  const merged = {
    ...getDefaultEnvConfig(),
    ...(kvCfg && typeof kvCfg === 'object' ? kvCfg : {}),
  };
  setMemoryCache('runtime-config', merged, 60000);
  return merged;
}
async function updateRuntimeConfig(patch) {
  const current = await getRuntimeConfig();
  const next = { ...current, ...patch };
  setMemoryCache('runtime-config', next, 60000);
  await kvPutJson('runtime-settings', next);
  return next;
}
async function incrementStat(name) {
  const count = (pendingStats.get(name) || 0) + 1;
  if (count >= 5) {
    pendingStats.delete(name);
    const key = `stat-${name}`;
    const current = Number((await nfd.get(key)) || 0);
    await nfd.put(key, String(current + count));
  } else {
    pendingStats.set(name, count);
  }
}
async function getStatCount(name) {
  const key = `stat-${name}`;
  const fromKv = Number((await nfd.get(key)) || 0);
  const fromMem = Number(pendingStats.get(name) || 0);
  return fromKv + fromMem;
}
async function checkCooldown(key, cooldownMs) {
  const now = Date.now();
  const mem = getMemoryCache(`cd-${key}`);
  if (mem && now - mem < cooldownMs) return false;

  const lastSentAt = Number((await nfd.get(key)) || 0);
  if (lastSentAt && now - lastSentAt < cooldownMs) {
    setMemoryCache(`cd-${key}`, lastSentAt, cooldownMs);
    return false;
  }

  setMemoryCache(`cd-${key}`, now, cooldownMs);
  await nfd.put(key, String(now));
  return true;
}
async function sendCooldownPlainText(chatId, key, text, cooldownMs) {
  const allowed = await checkCooldown(key, cooldownMs);
  if (!allowed) return null;
  return sendPlainText(chatId, text);
}
async function fetchRemoteDb(url, ttl = FRAUD_CACHE_TTL) {
  const cacheKey = `remote-${url}`;
  const cached = getMemoryCache(cacheKey);
  if (cached) return cached;

  const kvBackupKey = `backup-${url}`;
  try {
    const text = await fetch(url).then((r) => r.text());
    const lines = text.split(/\r?\n/).map((v) => v.trim()).filter(Boolean);
    setMemoryCache(cacheKey, lines, ttl);
    // Background backup to KV for offline resilience
    await kvPutJson(kvBackupKey, lines, { expirationTtl: 7 * 24 * 3600 });
    return lines;
  } catch (e) {
    console.log(JSON.stringify({ error: 'fetch-remote-db-failed', url, message: e.message }));
    // Fallback to KV backup if network/remote fails
    const backup = await kvGetJson(kvBackupKey, null);
    if (Array.isArray(backup) && backup.length > 0) {
      setMemoryCache(cacheKey, backup, ttl);
      return backup;
    }
    return [];
  }
}
async function isFraud(id) {
  const lines = await fetchRemoteDb(getFraudDbUrl());
  return lines.includes(String(id));
}
async function fetchKeywordDb() {
  return fetchRemoteDb(getKeywordDbUrl());
}
async function fetchTextOrDefault(url, fallback) {
  if (!url) return fallback;
  const cached = getMemoryCache(`text-${url}`);
  if (cached) return cached;
  try {
    const response = await fetch(url);
    if (response.ok) {
      const text = await response.text();
      setMemoryCache(`text-${url}`, text, 10 * 60 * 1000);
      return text;
    }
    return fallback;
  } catch (error) {
    console.log(JSON.stringify({ error: 'fetch-text-failed', url, message: error.message }));
    return fallback;
  }
}

// --- MODULE: telegram.js ---
// ==============================================================================
// src/telegram.js - Telegram API Client, Message Formatting & Keyboard Builders
// ==============================================================================
function apiUrl(methodName, params = null) {
  const token = getToken();
  const query = params ? `?${new URLSearchParams(params).toString()}` : '';
  return `https://api.telegram.org/bot${token}/${methodName}${query}`;
}
async function requestTelegram(methodName, body = {}) {
  try {
    const response = await fetch(apiUrl(methodName), {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    const data = await response.json();
    if (!data.ok) {
      console.log(JSON.stringify({ methodName, error: data.description, body }));
    }
    return data;
  } catch (error) {
    console.log(JSON.stringify({ methodName, error: error.message, body }));
    return { ok: false, description: error.message };
  }
}
function sendMessage(msg = {}) {
  return requestTelegram('sendMessage', msg);
}
function editMessageText(msg = {}) {
  return requestTelegram('editMessageText', {
    parse_mode: PARSE_MODE,
    link_preview_options: { is_disabled: true },
    ...msg,
  });
}
function copyMessage(msg = {}) {
  return requestTelegram('copyMessage', msg);
}
function forwardMessage(msg = {}) {
  return requestTelegram('forwardMessage', msg);
}
function deleteMessage(msg = {}) {
  return requestTelegram('deleteMessage', msg);
}
function answerCallbackQuery(msg = {}) {
  return requestTelegram('answerCallbackQuery', msg);
}
function escapeMarkdown(value = '') {
  return String(value).replace(/[_*[\]()~`>#+\-=|{}.!\\]/g, '\\$&');
}
function sendMarkdown(chatId, text, extra = {}) {
  return sendMessage({
    chat_id: chatId,
    text,
    parse_mode: PARSE_MODE,
    link_preview_options: { is_disabled: true },
    ...extra,
  });
}
function sendPlainText(chatId, text, extra = {}) {
  return sendMessage({
    chat_id: chatId,
    text,
    ...extra,
  });
}
function mdLine(label, value) {
  return `*${escapeMarkdown(label)}:* ${escapeMarkdown(value || '-')}`;
}
function getMessageText(message) {
  return message.text || message.caption || '';
}
function getCommand(message) {
  const text = (message.text || '').trim();
  return text.startsWith('/') ? text.split(/\s+/)[0].split('@')[0].toLowerCase() : '';
}
function getCommandArgs(message) {
  const text = (message.text || '').trim();
  const firstSpace = text.search(/\s/);
  return firstSpace === -1 ? '' : text.slice(firstSpace).trim();
}
function buildUserName(user = {}) {
  const nickname = [user.first_name, user.last_name].filter(Boolean).join(' ').trim();
  if (nickname) return nickname;
  if (user.username) return `@${user.username}`;
  return String(user.id || '');
}
function formatStartMessage(template, user) {
  const username = escapeMarkdown(buildUserName(user));
  return template
    .replaceAll('{username}', username)
    .replaceAll('{用户名}', username);
}
function buildMessageInfo(message, count = 1) {
  const user = message.from || {};
  const lines = [
    '*人偶收到新留言*',
    mdLine('客人', `${buildUserName(user)} (${user.id || message.chat.id})`),
  ];
  if (user.username) {
    lines.push(mdLine('用户名', `@${user.username}`));
  }
  if (message.chat?.type && message.chat.type !== 'private') {
    lines.push(mdLine('来源会话', `${message.chat.title || message.chat.id} / ${message.chat.type}`));
  }
  if (count > 1) {
    lines.push(mdLine('连续留言', `${count} 条`));
  }
  return lines.join('\n');
}
function buildGuestInfo(message) {
  const user = message.from || {};
  return {
    chatId: String(message.chat.id),
    userId: String(user.id || message.chat.id),
    name: buildUserName(user),
    username: user.username ? `@${user.username}` : '',
    languageCode: user.language_code || '',
    chatType: message.chat?.type || '',
    chatTitle: message.chat?.title || '',
    firstSeenAt: Date.now(),
    lastSeenAt: Date.now(),
  };
}
function formatGuestInfo(info = {}) {
  return [
    '*留言人信息*',
    mdLine('昵称', info.name || '-'),
    mdLine('用户名', info.username || '-'),
    mdLine('用户ID', info.userId || info.chatId || '-'),
    mdLine('会话ID', info.chatId || '-'),
    mdLine('语言', info.languageCode || '-'),
    mdLine('会话类型', info.chatType || '-'),
    mdLine('会话标题', info.chatTitle || '-'),
    mdLine('最后留言', info.lastSeenAt ? new Date(info.lastSeenAt).toISOString() : '-'),
  ].join('\n');
}
function adminMessageKeyboard() {
  return {
    inline_keyboard: [
      [
        { text: '回复', callback_data: 'reply' },
        { text: '信息', callback_data: 'info' },
        { text: '撤回最近回复', callback_data: 'revoke:last' },
      ],
      [
        { text: '屏蔽', callback_data: 'block' },
        { text: '解除屏蔽', callback_data: 'unblock' },
        { text: '检查', callback_data: 'checkblock' },
      ],
    ],
  };
}
function revokeReplyKeyboard(guestChatId, messageId) {
  return {
    inline_keyboard: [[
      { text: '撤回这条回复', callback_data: `revoke:${guestChatId}:${messageId}` },
    ]],
  };
}

// --- MODULE: moderation.js ---
// ==============================================================================
// src/moderation.js - Moderation Engine (Blacklist, Username, Avatar & Regex Keywords)
// ==============================================================================
import {
  cachedKvGetJson,
  cachedKvPutJson,
  getMemoryCache,
  setMemoryCache,
  kvGetJson,
  kvPutJson,
  incrementStat,
  fetchKeywordDb,
} from './cache.js';
function normalizeMessageText(text = '') {
  if (!text || typeof text !== 'string') return '';
  return text
    // Strip zero-width, invisible & direction marks
    .replace(/[\u200B-\u200F\uFEFF\u2060\u180E\u00AD]/g, '')
    // Convert full-width ASCII to standard half-width
    .replace(/[\uFF01-\uFF5E]/g, (ch) => String.fromCharCode(ch.charCodeAt(0) - 0xfee0))
    // Convert full-width space to standard space
    .replace(/\u3000/g, ' ')
    // Normalize multi-whitespace
    .replace(/\s+/g, ' ')
    .trim();
}
function parseKeywordRule(rawRule) {
  const raw = String(rawRule || '').trim();
  if (!raw) return null;

  const regexMatch = raw.match(/^\/(.+)\/([a-z]*)$/i);
  if (regexMatch) {
    const [, pattern, flags] = regexMatch;
    try {
      const safeFlags = flags.includes('i') ? flags : `${flags}i`;
      const regex = new RegExp(pattern, safeFlags);
      return {
        raw,
        isRegex: true,
        regex,
      };
    } catch (err) {
      console.log(JSON.stringify({ error: 'invalid-regex-rule', raw, message: err.message }));
      return {
        raw,
        isRegex: false,
        text: raw.toLowerCase(),
      };
    }
  }

  return {
    raw,
    isRegex: false,
    text: raw.toLowerCase(),
  };
}
async function isUserBlocked(chatId) {
  return cachedKvGetJson(`isblocked-${chatId}`, 60000, false);
}
async function setUserBlocked(chatId, blocked) {
  return cachedKvPutJson(`isblocked-${chatId}`, blocked, {}, 60000);
}
async function checkUserHasPhoto(userId) {
  const numericId = Number(userId);
  if (!numericId || Number.isNaN(numericId) || numericId <= 0) return true;

  const key = `has-photo-${numericId}`;
  const cached = getMemoryCache(key);
  if (typeof cached === 'boolean') return cached;

  const kvVal = await kvGetJson(key, null);
  if (typeof kvVal === 'boolean') {
    setMemoryCache(key, kvVal, kvVal ? 3600000 : 300000);
    return kvVal;
  }

  try {
    const res = await requestTelegram('getUserProfilePhotos', { user_id: numericId, limit: 1 });
    if (!res.ok) return true; // fail open on error
    const hasPhoto = Boolean(res.result && Number(res.result.total_count) > 0);
    const ttl = hasPhoto ? 3600 : 300;
    setMemoryCache(key, hasPhoto, ttl * 1000);
    await kvPutJson(key, hasPhoto, { expirationTtl: ttl });
    return hasPhoto;
  } catch (e) {
    console.log(JSON.stringify({ error: 'checkUserHasPhoto-failed', userId, message: e.message }));
    return true;
  }
}
async function getKeywordRules() {
  const cacheKey = 'merged-keyword-rules';
  const cached = getMemoryCache(cacheKey);
  if (cached) return cached;

  const fromKv = await cachedKvGetJson('blocked-keywords', 120000, []);
  const fromDb = await fetchKeywordDb();
  const rawList = Array.from(new Set([...fromDb, ...asArray(fromKv)]));

  const parsedRules = rawList.map(parseKeywordRule).filter(Boolean);
  setMemoryCache(cacheKey, parsedRules, 60000);
  return parsedRules;
}
async function findBlockedKeyword(message) {
  const rawContent = getMessageText(message);
  if (!rawContent) return null;

  const normalized = normalizeMessageText(rawContent);
  const lowerNormalized = normalized.toLowerCase();
  const rules = await getKeywordRules();

  for (const rule of rules) {
    if (rule.isRegex && rule.regex) {
      const match = normalized.match(rule.regex);
      if (match) {
        return {
          matched: true,
          rule: rule.raw,
          snippet: match[0],
        };
      }
    } else if (rule.text) {
      if (lowerNormalized.includes(rule.text)) {
        return {
          matched: true,
          rule: rule.raw,
          snippet: rule.raw,
        };
      }
    }
  }

  return null;
}
async function recordKeywordViolation(message, keyword) {
  const chatId = String(message.chat.id);
  const key = `keyword-violation-${chatId}`;
  const current = await kvGetJson(key, { count: 0, expiresAt: 0 });
  const now = Date.now();
  const count = current.expiresAt > now ? Number(current.count || 0) + 1 : 1;
  const ttl = getKeywordViolationTtl();
  const record = {
    count,
    lastKeyword: keyword,
    updatedAt: now,
    expiresAt: now + ttl * 1000,
  };
  await kvPutJson(key, record, { expirationTtl: ttl });
  return record;
}
async function notifyKeywordBlocked(message, matchResult, violation, config) {
  await incrementStat('keyword-blocked');
  if (!config.notice_admin) return null;
  const adminUid = getAdminUid();
  if (!adminUid) return null;

  const ruleName = typeof matchResult === 'string' ? matchResult : matchResult.rule;
  const snippet = typeof matchResult === 'object' && matchResult?.snippet ? matchResult.snippet : '';

  const lines = [
    '*人偶拦下了一条留言*',
    mdLine('触发规则', ruleName),
  ];

  if (snippet && snippet !== ruleName) {
    lines.push(mdLine('命中切片', snippet));
  }

  lines.push(
    mdLine('累计次数', violation.count),
    mdLine('用户ID', message.chat.id),
    mdLine('客人', buildUserName(message.from || {})),
  );

  if (config.auto_block && violation.count >= config.violation_limit) {
    lines.push(mdLine('处理', '已自动拉入黑名单'));
  }
  return sendMarkdown(adminUid, lines.join('\n'));
}

// --- MODULE: pipeline.js ---
// ==============================================================================
// src/pipeline.js - Message Buffering, Delayed Aggregation & Batch Forwarding
// ==============================================================================

import {
  MESSAGE_MAP_TTL,
  NOTIFY_INTERVAL,
  DEFAULT_NOTIFICATION,
  getAdminUid,
  getUserAckCooldownMs,
  getCommandWarningCooldownMs,
  getNotificationUrl,
  asArray,
  sleep,
} from './config.js';
import {
  cachedKvGetJson,
  cachedKvPutJson,
  getMemoryCache,
  setMemoryCache,
  kvGetJson,
  kvPutJson,
  getRuntimeConfig,
  incrementStat,
  sendCooldownPlainText,
  isFraud,
  fetchTextOrDefault,
} from './cache.js';
import {
  sendMarkdown,
  copyMessage,
  forwardMessage,
  mdLine,
  buildMessageInfo,
  buildGuestInfo,
  adminMessageKeyboard,
} from './telegram.js';
import {
  isUserBlocked,
  setUserBlocked,
  checkUserHasPhoto,
  findBlockedKeyword,
  recordKeywordViolation,
  notifyKeywordBlocked,
} from './moderation.js';
async function rememberGuestInfo(message) {
  const chatId = String(message.chat.id);
  const key = `guest-info-${chatId}`;
  const previous = await cachedKvGetJson(key, 300000, null);
  const next = {
    ...buildGuestInfo(message),
    firstSeenAt: previous?.firstSeenAt || Date.now(),
  };
  await cachedKvPutJson(key, next, {}, 300000);
  return next;
}
async function rememberMessageMap(adminMessageId, guestChatId) {
  setMemoryCache(`msg-map-${adminMessageId}`, String(guestChatId), 3600000);
  return kvPutJson(`msg-map-${adminMessageId}`, String(guestChatId), {
    expirationTtl: MESSAGE_MAP_TTL,
  });
}
async function getMappedGuestId(adminMessage) {
  const replyMessageId = adminMessage?.reply_to_message?.message_id;
  if (!replyMessageId) return null;
  const cached = getMemoryCache(`msg-map-${replyMessageId}`);
  if (cached) return cached;
  return kvGetJson(`msg-map-${replyMessageId}`, null);
}
async function handleGuestMessage(message) {
  const chatId = String(message.chat.id);
  const config = await getRuntimeConfig();
  const warningCooldown = getCommandWarningCooldownMs();

  // Parallelize non-dependent analytics and info recording with user check
  const [isBlocked] = await Promise.all([
    isUserBlocked(chatId),
    incrementStat('guest-message'),
    rememberGuestInfo(message),
  ]);

  if (isBlocked) {
    await incrementStat('blocked-user-message');
    return sendCooldownPlainText(chatId, `blocked-notice-${chatId}`, '这里暂时不能继续留言了喵。', warningCooldown);
  }

  if (config.req_username && !message.from?.username) {
    await incrementStat('no-username-blocked');
    return sendCooldownPlainText(
      chatId,
      `no-username-${chatId}`,
      '请先在 Telegram 设置用户名（Username / @xxx）后再留言喵。',
      warningCooldown,
    );
  }

  if (config.req_photo) {
    const userId = message.from?.id || message.chat.id;
    const hasPhoto = await checkUserHasPhoto(userId);
    if (!hasPhoto) {
      await incrementStat('no-photo-blocked');
      return sendCooldownPlainText(
        chatId,
        `no-photo-${chatId}`,
        '请先在 Telegram 设置个人头像后再留言喵。',
        warningCooldown,
      );
    }
  }

  if (config.delay_seconds > 0) {
    return handleDelayedGuestMessage(message, config);
  }

  return processGuestMessageBatch([message], config);
}
async function handleDelayedGuestMessage(message, config) {
  const chatId = String(message.chat.id);
  const batchKey = `pending-msgs-${chatId}`;
  const tokenKey = `pending-token-${chatId}`;

  const current = asArray(await kvGetJson(batchKey, []));
  if (!current.some((m) => m.message_id === message.message_id)) {
    current.push(message);
  }

  const token = `${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  await kvPutJson(batchKey, current, { expirationTtl: 300 });
  await kvPutJson(tokenKey, token, { expirationTtl: 300 });

  if (current.length >= 10) {
    await kvPutJson(batchKey, null, { expirationTtl: 60 });
    await kvPutJson(tokenKey, null, { expirationTtl: 60 });
    return processGuestMessageBatch(current, config);
  }

  await sleep(config.delay_seconds * 1000);

  const activeToken = await kvGetJson(tokenKey, null);
  if (activeToken !== token) {
    return;
  }

  const finalBatch = asArray(await kvGetJson(batchKey, []));
  await kvPutJson(batchKey, null, { expirationTtl: 60 });
  await kvPutJson(tokenKey, null, { expirationTtl: 60 });

  if (!finalBatch.length) return;
  return processGuestMessageBatch(finalBatch, config);
}
async function processGuestMessageBatch(messages, config = null) {
  if (!messages || !messages.length) return;
  if (!config) config = await getRuntimeConfig();

  const firstMessage = messages[0];
  const chatId = String(firstMessage.chat.id);
  const adminUid = getAdminUid();

  const isBlocked = await isUserBlocked(chatId);
  if (isBlocked) {
    await incrementStat('blocked-user-message');
    return;
  }

  let blockedResult = null;
  let violatingMessage = null;
  for (const msg of messages) {
    const match = await findBlockedKeyword(msg);
    if (match && match.matched) {
      blockedResult = match;
      violatingMessage = msg;
      break;
    }
  }

  if (blockedResult) {
    const targetMsg = violatingMessage || firstMessage;
    const violation = await recordKeywordViolation(targetMsg, blockedResult.rule);
    if (config.auto_block && violation.count >= config.violation_limit) {
      await setUserBlocked(chatId, true);
      await incrementStat('keyword-auto-blocked');
    }
    await notifyKeywordBlocked(targetMsg, blockedResult, violation, config);
    if (config.notice_user) {
      const text = violation.count >= config.violation_limit
        ? '多次发送不能转达的内容，这里暂时不能继续留言了喵。'
        : '这条留言含有暂时不能转达的词，人偶先收起来了喵。';
      return sendCooldownPlainText(chatId, `keyword-notice-${chatId}`, text, getCommandWarningCooldownMs());
    }
    return;
  }

  if (!adminUid) {
    console.log(JSON.stringify({ error: 'no-admin-uid-configured', chatId }));
    return;
  }

  const infoReq = await sendMarkdown(adminUid, buildMessageInfo(firstMessage, messages.length));
  if (infoReq.ok) {
    await rememberMessageMap(infoReq.result.message_id, chatId);
  }

  let deliveredAny = false;
  for (let i = 0; i < messages.length; i++) {
    const msg = messages[i];
    const isLast = i === messages.length - 1;
    const extra = isLast ? { reply_markup: adminMessageKeyboard() } : {};

    const copyReq = await copyMessage({
      chat_id: adminUid,
      from_chat_id: msg.chat.id,
      message_id: msg.message_id,
      ...extra,
    });

    if (copyReq.ok) {
      deliveredAny = true;
      await rememberMessageMap(copyReq.result.message_id, chatId);
      continue;
    }

    const forwardReq = await forwardMessage({
      chat_id: adminUid,
      from_chat_id: msg.chat.id,
      message_id: msg.message_id,
    });

    if (forwardReq.ok) {
      deliveredAny = true;
      await rememberMessageMap(forwardReq.result.message_id, chatId);
      continue;
    }

    await sendMarkdown(
      adminUid,
      [
        '*人偶转达失败*',
        mdLine('用户ID', chatId),
        mdLine('错误', forwardReq.description || copyReq.description || 'Unknown error'),
      ].join('\n'),
    );
  }

  if (deliveredAny) {
    await handleGuestDelivered(messages[messages.length - 1], config);
  }
}
async function handleGuestDelivered(message, config = null) {
  const chatId = String(message.chat.id);
  await sendCooldownPlainText(
    chatId,
    `deliver-ack-${chatId}`,
    '留言已经交给管理人啦，人偶会乖乖等回信喵。',
    getUserAckCooldownMs(),
  );
  await handleNotify(message, config);
}
async function handleNotify(message, config = null) {
  if (!config) config = await getRuntimeConfig();
  const chatId = String(message.chat.id);
  const adminUid = getAdminUid();
  if (!adminUid) return;

  if (await isFraud(chatId)) {
    return sendMarkdown(adminUid, `*诈骗库命中*\n${mdLine('UID', chatId)}`);
  }

  if (!config.enable_notify) return;

  const lastMsgTime = await kvGetJson(`lastmsg-${chatId}`, 0);
  if (!lastMsgTime || Date.now() - Number(lastMsgTime) > NOTIFY_INTERVAL) {
    await nfd.put(`lastmsg-${chatId}`, String(Date.now()));
    const notification = await fetchTextOrDefault(getNotificationUrl(), DEFAULT_NOTIFICATION);
    return sendMarkdown(adminUid, notification);
  }
}

// --- MODULE: panel.js ---
// ==============================================================================
// src/panel.js - Interactive Inline Keyboard Control Panel (/panel)
// ==============================================================================
function buildSettingPanel(config, page = 'moderation') {
  if (page === 'forwarding') {
    const text = [
      '*⚙️ 人偶控制面板（2/2 转发与通知）*',
      '',
      mdLine('⏱️ 转发缓冲延迟', config.delay_seconds > 0 ? `${config.delay_seconds} 秒` : '关闭 (即时转发)'),
      mdLine('📢 拦截通知管理', config.notice_admin ? '开启' : '关闭'),
      mdLine('💬 拦截提示客人', config.notice_user ? '开启' : '关闭'),
      mdLine('💡 安全交易提醒', config.enable_notify ? '开启' : '关闭'),
      '',
      '💡 _点击下方按钮实时调节延迟或切换开关喵_',
    ].join('\n');

    const keyboard = {
      inline_keyboard: [
        [
          { text: `⏱️ 延迟: ${config.delay_seconds > 0 ? config.delay_seconds + 's' : '关闭'} ▾`, callback_data: 'setting:cycle:delay_seconds' },
          { text: `💡 交易提醒: ${config.enable_notify ? '✅' : '❌'}`, callback_data: 'setting:toggle:enable_notify' },
        ],
        [
          { text: `📢 通知管理: ${config.notice_admin ? '✅' : '❌'}`, callback_data: 'setting:toggle:notice_admin' },
          { text: `💬 提示客人: ${config.notice_user ? '✅' : '❌'}`, callback_data: 'setting:toggle:notice_user' },
        ],
        [
          { text: '⬅️ 🛡️ 审查设置', callback_data: 'setting:page:moderation' },
          { text: '⏱️ 转发与通知 (当前)', callback_data: 'setting:page:forwarding' },
        ],
        [
          { text: '🔄 刷新状态', callback_data: 'setting:refresh:forwarding' },
          { text: '❌ 关闭面板', callback_data: 'setting:close' },
        ],
      ],
    };
    return { text, keyboard };
  }

  // Default Page: moderation
  const text = [
    '*⚙️ 人偶控制面板（1/2 拦截审查）*',
    '',
    mdLine('👤 要求用户名', config.req_username ? '开启' : '关闭'),
    mdLine('🖼️ 要求个人头像', config.req_photo ? '开启' : '关闭'),
    mdLine('🚫 违规自动拉黑', config.auto_block ? '开启' : '关闭'),
    mdLine('🔢 自动拉黑阈值', `${config.violation_limit} 次`),
    '',
    '💡 _点击下方按钮实时切换开关或调节阈值喵_',
  ].join('\n');

  const keyboard = {
    inline_keyboard: [
      [
        { text: `👤 用户名: ${config.req_username ? '✅' : '❌'}`, callback_data: 'setting:toggle:req_username' },
        { text: `🖼️ 头像: ${config.req_photo ? '✅' : '❌'}`, callback_data: 'setting:toggle:req_photo' },
      ],
      [
        { text: `🚫 自动拉黑: ${config.auto_block ? '✅' : '❌'}`, callback_data: 'setting:toggle:auto_block' },
        { text: `🔢 阈值: ${config.violation_limit}次 ▾`, callback_data: 'setting:cycle:violation_limit' },
      ],
      [
        { text: '🛡️ 审查设置 (当前)', callback_data: 'setting:page:moderation' },
        { text: '⏱️ 转发与通知 ➡️', callback_data: 'setting:page:forwarding' },
      ],
      [
        { text: '🔄 刷新状态', callback_data: 'setting:refresh:moderation' },
        { text: '❌ 关闭面板', callback_data: 'setting:close' },
      ],
    ],
  };
  return { text, keyboard };
}
async function sendSettingPanel(chatId, page = 'moderation') {
  const config = await getRuntimeConfig();
  const { text, keyboard } = buildSettingPanel(config, page);
  return sendMarkdown(chatId, text, { reply_markup: keyboard });
}
async function handleSettingCallback(callbackQuery, data, messageId) {
  const adminUid = getAdminUid();
  const parts = data.split(':');
  const action = parts[1]; // 'page', 'toggle', 'cycle', 'refresh', 'close'
  const key = parts[2];

  if (action === 'close') {
    if (messageId && adminUid) {
      await deleteMessage({ chat_id: adminUid, message_id: messageId });
    }
    return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '已关闭控制面板' });
  }

  let currentPage = 'moderation';
  let toast = '已更新设置';

  if (action === 'page') {
    currentPage = key || 'moderation';
    toast = currentPage === 'forwarding' ? '已切换至 转发与通知' : '已切换至 拦截审查';
  } else if (action === 'refresh') {
    currentPage = key || 'moderation';
    invalidateMemoryCache('runtime-config');
    toast = '已刷新当前配置';
  } else if (action === 'toggle') {
    const config = await getRuntimeConfig();
    const nextVal = !config[key];
    await updateRuntimeConfig({ [key]: nextVal });
    currentPage = ['delay_seconds', 'notice_admin', 'notice_user', 'enable_notify'].includes(key) ? 'forwarding' : 'moderation';
    toast = `已${nextVal ? '开启' : '关闭'}`;
  } else if (action === 'cycle') {
    const config = await getRuntimeConfig();
    if (key === 'violation_limit') {
      const limits = [1, 2, 3, 5];
      const nextVal = limits[(limits.indexOf(config.violation_limit) + 1) % limits.length] || 3;
      await updateRuntimeConfig({ violation_limit: nextVal });
      toast = `拉黑阈值调整为: ${nextVal} 次`;
      currentPage = 'moderation';
    } else if (key === 'delay_seconds') {
      const delays = [0, 3, 5, 10, 15];
      const nextVal = delays[(delays.indexOf(config.delay_seconds) + 1) % delays.length] ?? 0;
      await updateRuntimeConfig({ delay_seconds: nextVal });
      toast = nextVal > 0 ? `转发延迟调整为: ${nextVal} 秒` : '转发延迟已关闭 (即时转发)';
      currentPage = 'forwarding';
    }
  }

  const updatedConfig = await getRuntimeConfig();
  const { text, keyboard } = buildSettingPanel(updatedConfig, currentPage);

  if (messageId && adminUid) {
    await editMessageText({
      chat_id: adminUid,
      message_id: messageId,
      text,
      reply_markup: keyboard,
    });
  }

  return answerCallbackQuery({
    callback_query_id: callbackQuery.id,
    text: toast,
    show_alert: false,
  });
}

// --- MODULE: admin.js ---
// ==============================================================================
// src/admin.js - Admin Commands, Callback Query Router & Guest Management
// ==============================================================================
import {
  kvGetJson,
  kvPutJson,
  cachedKvGetJson,
  cachedKvPutJson,
  invalidateMemoryCache,
  incrementStat,
  getStatCount,
  sendCooldownPlainText,
  fetchKeywordDb,
} from './cache.js';
import {
  sendMarkdown,
  sendPlainText,
  copyMessage,
  deleteMessage,
  answerCallbackQuery,
  escapeMarkdown,
  mdLine,
  getCommandArgs,
  buildUserName,
  formatGuestInfo,
  revokeReplyKeyboard,
} from './telegram.js';
async function rememberForceReplyPrompt(promptMessageId, guestChatId) {
  return kvPutJson(`force-reply-${promptMessageId}`, {
    guestChatId: String(guestChatId),
    createdAt: Date.now(),
  }, { expirationTtl: MESSAGE_MAP_TTL });
}
async function clearForceReplyPrompt(promptMessageId) {
  return kvPutJson(`force-reply-${promptMessageId}`, null, { expirationTtl: 60 });
}
async function clearRepliedPrompt(message) {
  const promptId = message.reply_to_message?.message_id;
  if (!promptId) return;
  const record = await kvGetJson(`force-reply-${promptId}`, null);
  if (!record) return;
  const adminUid = getAdminUid();
  if (adminUid) {
    await deleteMessage({ chat_id: adminUid, message_id: promptId });
  }
  await clearForceReplyPrompt(promptId);
}
async function handleAdminMessage(message, command) {
  const adminUid = getAdminUid();
  if (!adminUid) return;

  if (command === '/help') return sendAdminHelp();
  if (command === '/panel' || command === '/config') {
    return sendSettingPanel(adminUid, 'moderation');
  }
  if (command === '/stats') return sendStats();
  if (command === '/keywords') return listKeywords();
  if (command === '/addkeyword') return addKeyword(message);
  if (command === '/delkeyword') return deleteKeyword(message);
  if (command === '/synckeywords') return syncKeywordDb();

  if (command === '/block') return handleBlock(message);
  if (command === '/unblock') return handleUnBlock(message);
  if (command === '/checkblock') return checkBlock(message);

  const guestChatId = await getMappedGuestId(message);
  if (!guestChatId) {
    return sendAdminHelp('请先回复一条人偶转来的留言，或发送管理命令。');
  }

  const copied = await copyMessage({
    chat_id: guestChatId,
    from_chat_id: message.chat.id,
    message_id: message.message_id,
  });

  if (copied.ok) {
    await incrementStat('admin-replied');
    await kvPutJson(`last-reply-${guestChatId}`, {
      chatId: String(guestChatId),
      messageId: copied.result.message_id,
      adminMessageId: message.message_id,
      createdAt: Date.now(),
    });
    await clearRepliedPrompt(message);
    return sendMarkdown(adminUid, escapeMarkdown(`人偶已经转达给 UID:${guestChatId} 了喵`), {
      reply_parameters: { message_id: message.message_id },
      reply_markup: revokeReplyKeyboard(guestChatId, copied.result.message_id),
    });
  }

  await clearRepliedPrompt(message);
  return sendMarkdown(adminUid, escapeMarkdown(`转达失败：${copied.description || 'Unknown error'}`));
}
async function handleGuestAdminCommand(message, command) {
  const chatId = String(message.chat.id);
  const adminUid = getAdminUid();
  await incrementStat('guest-command-warning');
  if (adminUid) {
    await sendMarkdown(
      adminUid,
      [
        '*客人误触管理指令*',
        mdLine('指令', command),
        mdLine('用户ID', chatId),
        mdLine('客人', buildUserName(message.from || {})),
      ].join('\n'),
    );
  }
  return sendCooldownPlainText(
    chatId,
    `warn-command-${chatId}`,
    '这是管理人专用的小按钮喵。请直接发送想留言的内容，人偶会帮你转达。',
    getCommandWarningCooldownMs(),
  );
}
async function onCallbackQuery(callbackQuery) {
  const adminUid = getAdminUid();
  if (String(callbackQuery.from?.id) !== adminUid) {
    return answerCallbackQuery({
      callback_query_id: callbackQuery.id,
      text: '这是管理人专用按钮喵。',
      show_alert: false,
    });
  }

  const data = callbackQuery.data || '';
  const adminMessageId = callbackQuery.message?.message_id;

  // 1. Interactive Settings Panel Callbacks
  if (data.startsWith('setting:')) {
    return handleSettingCallback(callbackQuery, data, adminMessageId);
  }

  // 2. Message Forwarding & Guest Management Callbacks
  const guestChatId = adminMessageId ? await getMappedGuestId(callbackQuery.message) : null;

  if (data === 'reply') {
    if (!guestChatId) return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '找不到这位客人了喵。' });
    const prompt = await sendMarkdown(adminUid, escapeMarkdown(`请回复这条消息，人偶会转达给 UID:${guestChatId} 喵。`), {
      reply_parameters: { message_id: adminMessageId },
      reply_markup: {
        force_reply: true,
        input_field_placeholder: '输入要转达给客人的内容',
        selective: true,
      },
    });
    if (prompt.ok) {
      await rememberMessageMap(prompt.result.message_id, guestChatId);
      await rememberForceReplyPrompt(prompt.result.message_id, guestChatId);
    }
    return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '请回复人偶的新提示消息。' });
  }

  if (data === 'info') {
    if (!guestChatId) return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '找不到留言人信息了喵。' });
    const info = await cachedKvGetJson(`guest-info-${guestChatId}`, 300000, null);
    await sendMarkdown(adminUid, info ? formatGuestInfo(info) : escapeMarkdown(`没有找到 UID:${guestChatId} 的详细信息。`), {
      reply_parameters: { message_id: adminMessageId },
    });
    return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '已展开留言人信息。' });
  }

  if (data === 'block' || data === 'unblock' || data === 'checkblock') {
    if (!guestChatId) return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '找不到这位客人了喵。' });
    const text = await applyBlockAction(data, guestChatId);
    await sendMarkdown(adminUid, escapeMarkdown(text), {
      reply_parameters: { message_id: adminMessageId },
    });
    return answerCallbackQuery({ callback_query_id: callbackQuery.id, text });
  }

  if (data === 'revoke:last') {
    if (!guestChatId) return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '找不到这位客人了喵。' });
    const lastReply = await kvGetJson(`last-reply-${guestChatId}`, null);
    if (!lastReply?.messageId) {
      return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '还没有可撤回的回复喵。' });
    }
    return revokeReply(callbackQuery, lastReply.chatId || guestChatId, lastReply.messageId);
  }

  if (data.startsWith('revoke:')) {
    const [, chatId, messageId] = data.split(':');
    return revokeReply(callbackQuery, chatId, messageId);
  }

  return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '人偶还不认识这个按钮喵。' });
}
async function applyBlockAction(action, guestChatId) {
  const adminUid = getAdminUid();
  if (action === 'block') {
    if (String(guestChatId) === adminUid) return '人偶不能屏蔽主人自己喵。';
    await setUserBlocked(guestChatId, true);
    return `UID:${guestChatId} 已放入静音抽屉`;
  }
  if (action === 'unblock') {
    await setUserBlocked(guestChatId, false);
    return `UID:${guestChatId} 已从静音抽屉取出`;
  }
  const blocked = await isUserBlocked(guestChatId);
  return `UID:${guestChatId} ${blocked ? '正在静音抽屉里' : '可以正常留言'}`;
}
async function revokeReply(callbackQuery, chatId, messageId) {
  const adminUid = getAdminUid();
  if (!chatId || !messageId) {
    return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '撤回目标不完整喵。' });
  }
  const result = await deleteMessage({
    chat_id: chatId,
    message_id: Number(messageId),
  });
  if (!result.ok) {
    return answerCallbackQuery({
      callback_query_id: callbackQuery.id,
      text: `撤回失败：${result.description || 'Unknown error'}`,
      show_alert: true,
    });
  }
  if (adminUid) {
    await sendMarkdown(adminUid, escapeMarkdown(`已撤回发给 UID:${chatId} 的回复。`));
  }
  return answerCallbackQuery({ callback_query_id: callbackQuery.id, text: '已撤回。' });
}
async function resolveTargetGuestId(message) {
  const args = getCommandArgs(message);
  if (args && /^\d+$/.test(args)) {
    return args;
  }
  return getMappedGuestId(message);
}
async function handleBlock(message) {
  const adminUid = getAdminUid();
  const guestChatId = await resolveTargetGuestId(message);
  if (!guestChatId) return sendAdminHelp('用法：回复一条客人的留言发送 /block，或直接发送 `/block 用户ID`。');
  if (String(guestChatId) === adminUid) {
    return sendPlainText(adminUid, '人偶不能屏蔽主人自己喵。');
  }

  await setUserBlocked(guestChatId, true);
  return sendMarkdown(adminUid, escapeMarkdown(`UID:${guestChatId} 已放入静音抽屉`));
}
async function handleUnBlock(message) {
  const adminUid = getAdminUid();
  const guestChatId = await resolveTargetGuestId(message);
  if (!guestChatId) return sendAdminHelp('用法：回复一条客人的留言发送 /unblock，或直接发送 `/unblock 用户ID`。');

  await setUserBlocked(guestChatId, false);
  return sendMarkdown(adminUid, escapeMarkdown(`UID:${guestChatId} 已从静音抽屉取出`));
}
async function checkBlock(message) {
  const adminUid = getAdminUid();
  const guestChatId = await resolveTargetGuestId(message);
  if (!guestChatId) return sendAdminHelp('用法：回复一条客人的留言发送 /checkblock，或直接发送 `/checkblock 用户ID`。');

  const blocked = await isUserBlocked(guestChatId);
  return sendMarkdown(adminUid, escapeMarkdown(`UID:${guestChatId} ${blocked ? '正在静音抽屉里' : '可以正常留言'}`));
}
async function sendAdminHelp(prefix = '') {
  const adminUid = getAdminUid();
  if (!adminUid) return;
  const lines = [
    prefix && escapeMarkdown(prefix),
    '*人偶管理手册*',
    '`/panel` 打开控制面板',
    '`/stats` 查看人偶今日工作记录',
    '`/block [UID]` 把客人放入静音抽屉（支持回复或直接带UID）',
    '`/unblock [UID]` 把客人从静音抽屉取出（支持回复或直接带UID）',
    '`/checkblock [UID]` 查看客人留言状态（支持回复或直接带UID）',
    '`/addkeyword 关键词` 添加不能转达的词',
    '`/delkeyword 关键词` 删除不能转达的词',
    '`/keywords` 查看关键词小纸条',
    '`/synckeywords` 从 keyword\\.db 同步关键词到小纸条',
    '',
    '直接回复人偶转来的留言，就会把内容转达给原来的客人喵。',
  ].filter(Boolean);
  return sendMarkdown(adminUid, lines.join('\n'));
}
async function listKeywords() {
  const adminUid = getAdminUid();
  if (!adminUid) return;
  const rules = await getKeywordRules();
  if (!rules.length) {
    return sendMarkdown(adminUid, '关键词小纸条还是空的喵。');
  }
  const lines = rules.map((rule) => {
    if (rule.isRegex) {
      return `\\- \\[正则\\] \`${escapeMarkdown(rule.raw)}\``;
    }
    return `\\- ${escapeMarkdown(rule.raw)}`;
  });
  return sendMarkdown(adminUid, ['*关键词小纸条*', ...lines].join('\n'));
}
async function addKeyword(message) {
  const adminUid = getAdminUid();
  if (!adminUid) return;
  const keyword = getCommandArgs(message);
  if (!keyword) return sendMarkdown(adminUid, '用法：`/addkeyword 关键词` 或 `/addkeyword /正则/i`');

  if (keyword.startsWith('/') && keyword.lastIndexOf('/') > 0) {
    const match = keyword.match(/^\/(.+)\/([a-z]*)$/i);
    if (match) {
      try {
        new RegExp(match[1], match[2] || 'i');
      } catch (err) {
        return sendMarkdown(adminUid, escapeMarkdown(`正则表达式语法错误：${err.message}`));
      }
    }
  }

  const current = await kvGetJson('blocked-keywords', []);
  const next = Array.from(new Set([...asArray(current), keyword]));
  await cachedKvPutJson('blocked-keywords', next);
  invalidateMemoryCache('merged-keyword-rules');
  return sendMarkdown(adminUid, escapeMarkdown(`已把「${keyword}」写进关键词小纸条`));
}
async function deleteKeyword(message) {
  const adminUid = getAdminUid();
  if (!adminUid) return;
  const keyword = getCommandArgs(message);
  if (!keyword) return sendMarkdown(adminUid, '用法：`/delkeyword 关键词`');

  const current = await kvGetJson('blocked-keywords', []);
  const next = asArray(current).filter((item) => item !== keyword);
  await cachedKvPutJson('blocked-keywords', next);
  invalidateMemoryCache('merged-keyword-rules');
  return sendMarkdown(adminUid, escapeMarkdown(`已从关键词小纸条擦掉「${keyword}」`));
}
async function syncKeywordDb() {
  const adminUid = getAdminUid();
  if (!adminUid) return;
  const fromDb = await fetchKeywordDb();
  if (!fromDb.length) {
    return sendMarkdown(adminUid, 'keyword\\.db 里没有关键词喵。');
  }
  const current = asArray(await kvGetJson('blocked-keywords', []));
  const merged = Array.from(new Set([...current, ...fromDb]));
  await cachedKvPutJson('blocked-keywords', merged);
  invalidateMemoryCache('merged-keyword-rules');
  const added = merged.length - current.length;
  return sendMarkdown(
    adminUid,
    escapeMarkdown(`已从 keyword.db 同步 ${fromDb.length} 个关键词，新增 ${added} 个，小纸条现共 ${merged.length} 个`),
  );
}
async function sendStats() {
  const adminUid = getAdminUid();
  if (!adminUid) return;
  const names = [
    'guest-message',
    'admin-replied',
    'keyword-blocked',
    'keyword-auto-blocked',
    'no-username-blocked',
    'no-photo-blocked',
    'guest-command-warning',
    'blocked-user-message',
  ];
  const values = await Promise.all(names.map((name) => getStatCount(name)));
  const lines = names.map((name, index) => mdLine(name, String(values[index] ?? 0)));
  return sendMarkdown(adminUid, ['*人偶工作记录*', ...lines].join('\n'));
}

// --- MODULE: index.js ---
// ==============================================================================
// src/index.js - Cloudflare Worker Entry & Webhook Router
// Supports Cloudflare Git Auto-Deploy (Module Worker) & Legacy Service Worker
// ==============================================================================

import {
  WEBHOOK,
  ADMIN_COMMANDS,
  DEFAULT_START_MESSAGE,
  getSecret,
  getAdminUid,
  getStartMsgUrl,
} from './config.js';
async function handleFetch(request, env = null, ctx = null) {
  if (env) {
    Object.assign(globalThis, env);
  }

  const url = new URL(request.url);
  const secret = getSecret();

  if (url.pathname === WEBHOOK) {
    return handleWebhook(request, ctx);
  } else if (url.pathname === '/registerWebhook') {
    const providedSecret = url.searchParams.get('secret') || request.headers.get('X-Telegram-Bot-Api-Secret-Token') || request.headers.get('x-secret');
    if (secret && providedSecret !== secret) {
      return new Response('Unauthorized: Secret mismatch', { status: 403 });
    }
    return registerWebhook(url);
  } else if (url.pathname === '/unRegisterWebhook') {
    const providedSecret = url.searchParams.get('secret') || request.headers.get('X-Telegram-Bot-Api-Secret-Token') || request.headers.get('x-secret');
    if (secret && providedSecret !== secret) {
      return new Response('Unauthorized: Secret mismatch', { status: 403 });
    }
    return unRegisterWebhook();
  } else {
    return new Response('No handler for this request');
  }
}
async function handleWebhook(request, ctx = null) {
  const secret = getSecret();
  if (secret && request.headers.get('X-Telegram-Bot-Api-Secret-Token') !== secret) {
    return new Response('Unauthorized', { status: 403 });
  }

  const update = await request.json();
  if (ctx && typeof ctx.waitUntil === 'function') {
    ctx.waitUntil(onUpdate(update));
  } else {
    onUpdate(update);
  }
  return new Response('Ok');
}
async function onUpdate(update) {
  try {
    if (update.message) {
      await onMessage(update.message);
    } else if (update.callback_query) {
      await onCallbackQuery(update.callback_query);
    }
  } catch (err) {
    console.log(JSON.stringify({ error: 'onUpdate-failed', message: err.message, stack: err.stack }));
  }
}
async function onMessage(message) {
  if (!message?.chat?.id) return;

  const adminUid = getAdminUid();
  const isAdmin = Boolean(adminUid && String(message.chat.id) === adminUid);
  const command = getCommand(message);

  if (command === '/start') {
    if (isAdmin) {
      return sendMarkdown(
        message.chat.id,
        '*管理人好喵*，这里是人偶！\n\n发送 `/panel` 可打开交互式控制面板，发送 `/help` 可查看管理手册。',
      );
    }
    const startMsg = await fetchTextOrDefault(getStartMsgUrl(), DEFAULT_START_MESSAGE);
    return sendMarkdown(message.chat.id, formatStartMessage(startMsg, message.from || {}));
  }

  if (isAdmin) {
    return handleAdminMessage(message, command);
  }

  if (ADMIN_COMMANDS.has(command)) {
    return handleGuestAdminCommand(message, command);
  }

  return handleGuestMessage(message);
}
async function registerWebhook(requestUrl) {
  const webhookUrl = `${requestUrl.protocol}//${requestUrl.hostname}${WEBHOOK}`;
  const secret = getSecret();
  const r = await fetch(apiUrl('setWebhook'), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      url: webhookUrl,
      secret_token: secret,
      allowed_updates: ['message', 'callback_query'],
      drop_pending_updates: true,
    }),
  }).then((response) => response.json());
  return new Response(r.ok ? 'Ok' : JSON.stringify(r, null, 2));
}
async function unRegisterWebhook() {
  const r = await fetch(apiUrl('deleteWebhook'), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ drop_pending_updates: true }),
  }).then((response) => response.json());
  return new Response(r.ok ? 'Ok' : JSON.stringify(r, null, 2));
}

// Cloudflare Workers Native Module Export (Used by Cloudflare Git Integration & Wrangler)

// Legacy Service Worker Syntax Fallback (Used when pasted directly into Cloudflare Quick Edit)
if (typeof addEventListener === 'function') {
  addEventListener('fetch', (event) => {
    event.respondWith(handleFetch(event.request, null, event));
  });
}
